service: contactLists

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    COLL_NAME: artistContactList
    DB_NAME: crowdaaDev
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}
    STAGE: ${self:provider.stage}
    AWS_REGION: ${self:provider.region}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}

functions:
  blastContactListEmail:
    handler: handler.handleBlastContactListEmail
    events:
      - http:
          path: contactLists/{id}/blast/email
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
  blastContactListText:
    handler: handler.handleBlastContactListText
    events:
      - http:
          path: contactLists/{id}/blast/text
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
  getContactList:
    handler: handler.handleGetContactList
    events:
      - http:
          path: contactLists/{id}
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
  

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true

resources:
  Resources:
    ApiGatewayMethodContactlistsIdVarGet:
      Properties:
        RequestParameters:
          method.request.header.Authorization: true
          method.request.path.id: true
        Integration:
          RequestParameters:
            integration.request.path.id: method.request.path.id
          CacheNamespace: ApiGatewayMethodContactlistsIdVarGetCacheNS
          CacheKeyParameters:
            - method.request.header.Authorization
            - method.request.path.id
