service: contactLists

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  blastContactListEmail:
    handler: handlers/blastContactListEmail.default
    events:
      - http:
          path: contactLists/{id}/blast/email
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
  blastContactListText:
    handler: handlers/blastContactListText.default
    events:
      - http:
          path: contactLists/{id}/blast/text
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
  getContactList:
    handler: handlers/getContactList.default
    events:
      - http:
          path: contactLists/{id}
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
  

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3

package:
  individually: true

resources:
  Resources:
    ApiGatewayMethodContactlistsIdVarGet:
      Properties:
        RequestParameters:
          method.request.header.Authorization: true
          method.request.path.id: true
        Integration:
          RequestParameters:
            integration.request.path.id: method.request.path.id
          CacheNamespace: ApiGatewayMethodContactlistsIdVarGetCacheNS
          CacheKeyParameters:
            - method.request.header.Authorization
            - method.request.path.id
