service: contactLists

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 60
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    COLL_NAME: artistContactList
    DB_NAME: crowdaaDev
    MONGO_URL: ${self:custom.mongoDB.${self:provider.stage}}
    STAGE: ${self:provider.stage}
  apiGateway:
    restApiId: ${self:custom.apiGateway.restApiId.${self:provider.stage}}
    restApiRootResourceId: ${self:custom.apiGateway.restApiRootResourceId.${self:provider.stage}}

functions:
  blastContactListEmail:
    handler: handler.handleBlastContactListEmail
    events:
      - http:
          path: contactLists/{id}/blast/email
          method: post
          authorizer:
            arn: ${self:custom.authorizer.${self:provider.stage}}
            name: contactListsAuthorizer
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
  blastContactListText:
    handler: handler.handleBlastContactListText
    events:
      - http:
          path: contactLists/{id}/blast/text
          method: post
          authorizer:
            arn: ${self:custom.authorizer.${self:provider.stage}}
            name: contactListsAuthorizer
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
  getContactList:
    handler: handler.handleGetContactList
    events:
      - http:
          path: contactLists/{id}
          method: get
          authorizer:
            arn: ${self:custom.authorizer.${self:provider.stage}}
            name: contactListsAuthorizer
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
  

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  apiGateway:
    restApiId:
      dev: diqdv4fvol
      prod: xbtq2qqal5
    restApiRootResourceId:
      dev: aus9fmgcr3
      prod: hp7jubgyp7

  authorizer:
    dev: arn:aws:lambda:us-east-1:630176884077:function:account-dev-authorize
    prod: arn:aws:lambda:us-east-1:630176884077:function:account-prod-authorize

  mongoDB:
    dev: mongodb://crowdaaMS:b0cfc2ffd49b6f27af7ed0cda6a49025@mongodev.aws.crowdaa.com:27017/crowdaaDev
    prod: mongodb://crowdaaMS:9871e59eac27cc669218907c570da230@aws-eu-west-1-portal.10.dblayer.com:18012,aws-eu-west-1-portal.8.dblayer.com:18012/crowdaaDev?ssl=true

  webpackIncludeModules: true

resources:
  Resources:
    ApiGatewayMethodContactlistsIdVarGet:
      Properties:
        RequestParameters:
          method.request.header.Authorization: true
          method.request.path.id: true
        Integration:
          RequestParameters:
            integration.request.path.id: method.request.path.id
          CacheNamespace: ApiGatewayMethodContactlistsIdVarGetCacheNS
          CacheKeyParameters:
            - method.request.header.Authorization
            - method.request.path.id
