service: payouts

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 60
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    REGION: us-east-1
    COLL_NAME: payouts
    TX_CREDITS: 0.1
    STAGE: ${self:provider.stage}
    DB_NAME: crowdaaDev
    MONGO_URL: mongodb://crowdaaMS:9871e59eac27cc669218907c570da230@aws-eu-west-1-portal.10.dblayer.com:18012,aws-eu-west-1-portal.8.dblayer.com:18012/crowdaaDev?ssl=true
  apiGateway:
    restApiId: ${self:custom.apiGateway.restApiId.${self:provider.stage}}
    restApiRootResourceId: ${self:custom.apiGateway.restApiRootResourceId.${self:provider.stage}}

functions:
  getPayouts:
    handler: handler.handleGetPayouts
    events:
      - http:
          path: payouts/
          method: get
          authorizer:
            arn: ${self:custom.authorizer.${self:provider.stage}}
            name: payoutsAuthorizer
          cors: true
  putPayout:
    handler: handler.handlePutPayout
    events:
      - http:
          path: payouts/
          method: put
          authorizer:
            arn: ${self:custom.authorizer.${self:provider.stage}}
            name: payoutsAuthorizer
          cors: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  apiGateway:
    restApiId:
      dev: diqdv4fvol
      prod: xbtq2qqal5
    restApiRootResourceId:
      dev: aus9fmgcr3
      prod: hp7jubgyp7

  authorizer:
    dev: arn:aws:lambda:us-east-1:630176884077:function:account-dev-authorizeAdmin
    prod: arn:aws:lambda:us-east-1:630176884077:function:account-prod-authorizeAdmin

  webpackIncludeModules: true
