service: orders

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    REGION: us-east-1
    IOS_FEES: 0.3
    COLL_NAME: billing
    STAGE: ${self:provider.stage}
    DB_NAME: crowdaaDev
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}
    STRIPE_API_KEY: ${self:custom.STRIPE_API_KEY.${self:provider.stage}}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}

functions:
  openOrder:
    handler: handler.handleOpenOrder
    events:
      - http:
          path: orders/
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true

  payByStripe:
    handler: handlers/payByStripe.default
    events:
      - http:
          path: orders/stripe
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  STRIPE_API_KEY:
    dev: sk_test_wbtCudjJImb2OKWdxR1HvoTr
    prod: sk_live_LRPlsPVcghchBVfGKChUTdfV
  webpackIncludeModules: true
