service: orders

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  memorySize: 192
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment: ${file(../env.yml)}
  <<<:
    - environment:
      STRIPE_API_KEY: ${self:custom.STRIPE_API_KEY.${self:provider.stage}}
      MAILGUN_API_KEY: ${self:custom.MAILGUN_API_KEY.${self:provider.stage}}
      MAILGUN_DOMAIN: ${self:custom.MAILGUN_DOMAIN.${self:provider.stage}}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  openOrder:
    handler: handlers/openOrder.default
    events:
      - http:
          path: orders/
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true

  payByStripe:
    handler: handlers/payByStripe.default
    events:
      - http:
          path: orders/stripe
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-prune-plugin

package:
  individually: true

custom:
  prune:
    automatic: true
    number: 3
  STRIPE_API_KEY:
    dev: sk_test_wbtCudjJImb2OKWdxR1HvoTr
    preprod: sk_test_wbtCudjJImb2OKWdxR1HvoTr
    prod: sk_live_LRPlsPVcghchBVfGKChUTdfV
    awax: sk_live_LRPlsPVcghchBVfGKChUTdfV
  MAILGUN_API_KEY:
    dev: key-ee8f3c350f56cbe4002b9c00cce04769
    preprod: key-ee8f3c350f56cbe4002b9c00cce04769
    prod: key-ee8f3c350f56cbe4002b9c00cce04769
    awax: key-ee8f3c350f56cbe4002b9c00cce04769
  MAILGUN_DOMAIN:
    dev: mg.crowdaa.com
    preprod: mg.crowdaa.com
    prod: mg.crowdaa.com
    awax: mg.crowdaa.com
