export const ERROR_TYPE_AUTHORIZATION = 'Authorization';
export const ERROR_TYPE_CONFLICT = 'Conflict';
export const ERROR_TYPE_NOT_ALLOWED = 'NotAllowed';

export const APP_ALREADY_BUILD = 'APP_ALREADY_BUILD';
export const CONTEXT_AUTHORIZER_NO_USER = 'CONTEXTE_AUTHORIZER_NO_USER';
export const UNMANAGED_EXCEPTION = 'UNMANAGED_EXCEPTION';
export const APP_NOT_FOUND = 'APP_NOT_FOUND';
export const MISSING_ORGANIZATION = 'MISSING_ORGANIZATION';
export const CANNOT_CHANGE_IOS_NAME = 'CANNOT_CHANGE_IOS_NAME';
export const CANNOT_CHANGE_ANDROID_NAME = 'CANNOT_CHANGE_ANDROID_NAME';

export const CONTEXT_AUTHORIZER_NO_USER_CODE = 'CONTEXTE_AUTHORIZER_NO_USER';
export const MISSING_ORGANIZATION_CODE = 'MISSING_ORGANIZATION';

export const ERROR_TYPE_NOT_FOUND = 'NotFound';
export const APP_NOT_FOUND_CODE = 'APP_NOT_FOUND';

export const ERROR_TYPE_VALIDATION_ERROR = 'ValidationError';
export const MISSING_BODY_CODE = 'MISSING_BODY';

export const ERROR_TYPE_ACCESS = 'CannotAccess';
export const ORGANIZATION_PERMISSION_CODE = 'ORGANIZATION_PERMISSION';
export const APPLICATION_PERMISSION_CODE = 'APPLICATION_PERMISSION';

export const ERROR_TYPE_INTERNAL_EXCEPTION = 'InternalException';
export const APP_ALREADY_BUILD_CODE = 'APP_ALREADY_BUILD';
export const UNMANAGED_EXCEPTION_CODE = 'UNMANAGED_EXCEPTION';
