export const ERROR_TYPE_SETUP = 'Setup';
export const MISSING_ENVIRONMENT_VARIABLE_CODE = 'MISSING_ENVIRONMENT_VARIABLE';
export const CHAT_NOT_CONFIGURED_CODE = 'CHAT_NOT_CONFIGURED';

export const ERROR_TYPE_STRIPE = 'Stripe';
export const APP_ID_NOT_FOUND_CODE = 'APP_ID_NOT_FOUND';
export const SIGNATURE_CHECK_ERROR_CODE = 'SIGNATURE_CHECK_ERROR_CODE';
export const UNKNOWN_PRICE_ID_CODE = 'UNKNOWN_PRICE_ID';
export const CHECKOUT_SESSION_INSTANCIATION_FAILED_CODE =
  'CHECKOUT_SESSION_INSTANCIATION_FAILED';
export const STRIPE_MISSING_SUBSCRIPTION_ITEM_CODE =
  'STRIPE_MISSING_SUBSCRIPTION_ITEM';
export const STRIPE_VALID_SUBSCRIPTION_ALREADY_EXIST_CODE =
  'STRIPE_VALID_SUBSCRIPTION_ALREADY_EXIST';
export const STRIPE_SUBSCRIPTION_STATUS_NOT_ALLOWED_CODE =
  'STRIPE_SUBSCRIPTION_STATUS_NOT_ALLOWED';

export const ERROR_TYPE_AUTHORIZATION = 'Authorization';
export const ERROR_TYPE_CONFLICT = 'Conflict';

export const ERROR_TYPE_IAP = 'IAP';
export const INSUFFICIENT_BALANCE_FUNDS_CODE = 'INSUFFICIENT_BALANCE_FUNDS';
export const BALANCE_UPDATE_FAILED_CODE = 'BALANCE_UPDATE_FAILED';

export const ERROR_TYPE_NOT_ALLOWED = 'NotAllowed';
export const CANNOT_CHANGE_IOS_NAME_CODE = 'CANNOT_CHANGE_IOS_NAME';
export const CANNOT_CHANGE_ANDROID_NAME_CODE = 'CANNOT_CHANGE_ANDROID_NAME';
export const ORGANISATION_STILL_CONTAINS_APPLICATION_CODE =
  'ORGANISATION_STILL_CONTAINS_APPLICATION';
export const ORGANISATION_APPLE_TEAM_ALREADY_SETUP_CODE =
  'ORGANISATION_APPLE_TEAM_ALREADY_SETUP';
export const USER_NO_PERMISSIONS_CODE = 'USER_NO_PERMISSIONS';
export const USER_NO_ORGANIZATION_CODE = 'USER_NO_ORGANIZATION';
export const INVALID_WEBSITE_TYPE_CODE = 'INVALID_WEBSITE_TYPE';
export const NOT_ENOUGH_PERMISSIONS_CODE = 'NOT_ENOUGH_PERMISSIONS';
export const AT_LEAST_ONE_OWNER_CODE = 'AT_LEAST_ONE_OWNER';
export const AT_LEAST_ONE_ADMIN_CODE = 'AT_LEAST_ONE_ADMIN';
export const USER_ALREADY_EXISTS_CODE = 'USER_ALREADY_EXISTS';
export const APPLICATION_OUTSIDE_ORGANIZATION_CODE =
  'APPLICATION_OUTSIDE_ORGANIZATION';
export const APP_FEATURE_PLAN_QUOTA_EXCEEDED_CODE =
  'APP_FEATURE_PLAN_QUOTA_EXCEEDED';
export const USER_ALREADY_IN_ORGANIZATION_CODE = 'USER_ALREADY_IN_ORGANIZATION';
export const INVITATION_ALREADY_EXISTS_CODE = 'INVITATION_ALREADY_EXISTS';
export const DIFFERENT_BACKEND_TYPE_ALREADY_SET_CODE =
  'DIFFERENT_BACKEND_TYPE_ALREADY_SET';
export const SELF_USER_BLOCK_CODE = 'SELF_USER_BLOCK';
export const SELF_USER_REPORT_CODE = 'SELF_USER_REPORT';
export const ALREADY_REPORTED_CODE = 'ALREADY_REPORTED';
export const CONNECTION_REQUIRED_CODE = 'CONNECTION_REQUIRED';
export const IAP_POLL_DISABLED_CODE = 'IAP_POLL_DISABLED';
export const IAP_POLL_BEFORE_START_CODE = 'IAP_POLL_BEFORE_START';
export const IAP_POLL_AFTER_END_CODE = 'IAP_POLL_AFTER_END';
export const IAP_POLL_ALREADY_VOTED_CODE = 'IAP_POLL_ALREADY_VOTED';
export const IAP_POLL_FREE_QUOTA_EXCEEDED_CODE = 'IAP_POLL_FREE_QUOTA_EXCEEDED';
export const INVALID_USERNAME_CODE = 'INVALID_USERNAME';

export const ERROR_TYPE_NOT_FOUND = 'NotFound';
export const APP_NOT_FOUND_CODE = 'APP_NOT_FOUND';
export const WEBSITE_NOT_FOUND_CODE = 'WEBSITE_NOT_FOUND';
export const TEMPLATE_NOT_FOUND_CODE = 'TEMPLATE_NOT_FOUND';
export const ORGANIZATION_NOT_FOUND_CODE = 'ORGANIZATION_NOT_FOUND';
export const USER_NOT_FOUND_CODE = 'USER_NOT_FOUND';
export const LEGAL_DOCUMENT_NOT_FOUND_CODE = 'LEGAL_DOCUMENT_NOT_FOUND';
export const STRIPE_SUBSCRIPTION_NOT_FOUND_CODE =
  'STRIPE_SUBSCRIPTION_NOT_FOUND';
export const STRIPE_CUSTOMER_ID_NOT_FOUND_CODE = 'STRIPE_CUSTOMER_ID_NOT_FOUND';
export const CHECKOUT_SESSION_NOT_FOUND_CODE = 'CHECKOUT_SESSION_NOT_FOUND';
export const FEATURE_PLAN_NOT_FOUND_CODE = 'FEATURE_PLAN_NOT_FOUND';
export const INVITATION_NOT_FOUND_CODE = 'INVITATION_NOT_FOUND';
export const BOOKABLE_NOT_FOUND_CODE = 'BOOKABLE_NOT_FOUND';
export const TICKET_NOT_FOUND_CODE = 'TICKET_NOT_FOUND';
export const IAP_POLL_NOT_FOUND_CODE = 'IAP_POLL_NOT_FOUND';
export const IAP_POLL_OPTION_NOT_FOUND_CODE = 'IAP_POLL_OPTION_NOT_FOUND';
export const VIDEO_NOT_FOUND_CODE = 'VIDEO_NOT_FOUND';
export const LIVE_STREAM_NOT_FOUND_CODE = 'LIVE_STREAM_NOT_FOUND';
export const CATEGORY_NOT_FOUND_CODE = 'CATEGORY_NOT_FOUND';

export const ERROR_TYPE_VALIDATION_ERROR = 'ValidationError';
export const REQUEST_ORIGIN_NOT_ALLOWED_CODE = 'REQUEST_ORIGIN_NOT_ALLOWED';
export const TOO_OLD_CHECKOUT_SESSION_CODE = 'TOO_OLD_CHECKOUT_SESSION';
export const MISSING_BODY_CODE = 'MISSING_BODY';
export const MISSING_QUERY_PARAMETERS_CODE = 'MISSING_QUERY_PARAMETERS';
export const MISSING_CHECKOUT_SESSION_SUCCESS_URL_CODE =
  'MISSING_CHECKOUT_SESSION_SUCCESS_URL';
export const MISSING_SUBSCRIPTION_ID_CODE = 'MISSING_SUBSCRIPTION_ID';
export const MISSING_APPLICATION_CODE = 'MISSING_APPLICATION';
export const MISSING_ORGANIZATION_CODE = 'MISSING_ORGANIZATION';
export const MISSING_USER_CODE = 'MISSING_USER';
export const MISSING_PICTURE_CODE = 'MISSING_PICTURE';
export const INVALID_PICTURE_CODE = 'INVALID_PICTURE';
export const FEATURE_SPECIFICATION_NOT_VALID_CODE =
  'FEATURE_SPECIFICATION_NOT_VALID';
export const INVALID_ARGUMENT_VALUE_CODE = 'INVALID_ARGUMENT_VALUE';
export const INVALID_PLAN_ID_CODE = 'INVALID_PLAN_ID';
export const INVALID_INPUT_FORMAT_CODE = 'INVALID_INPUT_FORMAT';
export const INVALID_SELF_INVITATION_CODE = 'INVALID_SELF_INVITATION';
export const INVALID_EXPIRATION_DATA_INVITATION_CODE =
  'INVALID_EXPIRATION_DATA_INVITATION';
export const INVALID_CHALLENGE_CODE_INVITATION_CODE =
  'INVALID_CHALLENGE_CODE_INVITATION';
export const INVALID_LOCALE_CODE = 'INVALID_LOCALE';
export const MISSING_ARGUMENT_CODE = 'MISSING_ARGUMENT';
export const MISSING_INVITED_USER_CODE = 'MISSING_INVITED_USER';

export const ERROR_TYPE_ACCESS = 'CannotAccess';
export const SUPERADMIN_PERMISSION_CODE = 'SUPERADMIN_PERMISSION';
export const ORGANIZATION_PERMISSION_CODE = 'ORGANIZATION_PERMISSION';
export const APPLICATION_PERMISSION_CODE = 'APPLICATION_PERMISSION';
export const FEATURE_PERMISSION_CODE = 'FEATURE_PERMISSION';

export const ERROR_TYPE_INTERNAL_EXCEPTION = 'InternalException';
export const APP_ALREADY_BUILD_CODE = 'APP_ALREADY_BUILD';
export const WORDPRESS_PLAYLISTS_NOT_SET_CODE = 'WORDPRESS_PLAYLISTS_NOT_SET';
export const UNMANAGED_EXCEPTION_CODE = 'UNMANAGED_EXCEPTION';
export const PANIC_CODE = 'PANIC_EXCEPTION';
export const UPDATE_FAILURE_CODE = 'UPDATE_FAILURE';

export const ERROR_TYPE_LIMIT_EXCEEDED = 'LimitExceeded';
export const MAX_TICKETS_EXCEEDED_CODE = 'MAX_TICKETS_EXCEEDED';
export const MAX_USER_TICKETS_EXCEEDED_CODE = 'MAX_USER_TICKETS_EXCEEDED';

export const ERROR_TYPE_FORBIDDEN = 'Forbidden';
export const DELETE_OWNER_CODE = 'DELETE_OWNER_CODE';
export const INVALID_TOKEN_CODE = 'INVALID_TOKEN';

export const ERROR_TYPE_FOREIGN_API = 'Foreign API';

export const ERROR_TYPE_COMPUTE_ACTIVE_USERS = 'ComputeActiveUsers';
export const CALL_COMPUTE_ACTIVE_USERS_FOR_DAY_CODE =
  'CALL_COMPUTE_ACTIVE_USERS_FOR_DAY';

export const ERROR_TYPE_UNTESTED_CODE = 'UntestedCode';
export const DONT_USE_THIS_CODE = 'DONT_USE_THIS_CODE';
