export const ERROR_TYPE_SETUP = 'Setup';
export const MISSING_ENVIRONMENT_VARIABLE_CODE = 'MISSING_ENVIRONMENT_VARIABLE';

export const ERROR_TYPE_STRIPE = 'Stripe';
export const APP_ID_NOT_FOUND_CODE = 'APP_ID_NOT_FOUND';
export const WEBHOOK_ERROR_CODE = 'WEBHOOK_ERROR_CODE';
export const UNKNOWN_PRICE_ID_CODE = 'UNKNOWN_PRICE_ID';
export const CHECKOUT_SESSION_INSTANCIATION_FAILED_CODE =
  'CHECKOUT_SESSION_INSTANCIATION_FAILED';
export const STRIPE_MISSING_SUBSCRIPTION_ITEM_CODE =
  'STRIPE_MISSING_SUBSCRIPTION_ITEM';
export const STRIPE_VALID_SUBSCRIPTION_ALREADY_EXIST_CODE =
  'STRIPE_VALID_SUBSCRIPTION_ALREADY_EXIST';
export const STRIPE_SUBSCRIPTION_STATUS_NOT_ALLOWED_CODE =
  'STRIPE_SUBSCRIPTION_STATUS_NOT_ALLOWED';

export const ERROR_TYPE_AUTHORIZATION = 'Authorization';
export const ERROR_TYPE_CONFLICT = 'Conflict';

export const ERROR_TYPE_NOT_ALLOWED = 'NotAllowed';
export const CANNOT_CHANGE_IOS_NAME_CODE = 'CANNOT_CHANGE_IOS_NAME';
export const CANNOT_CHANGE_ANDROID_NAME_CODE = 'CANNOT_CHANGE_ANDROID_NAME';
export const ORGANISATION_STILL_CONTAINS_APPLICATION_CODE =
  'ORGANISATION_STILL_CONTAINS_APPLICATION';
export const ORGANISATION_APPLE_TEAM_ALREADY_SETUP_CODE =
  'ORGANISATION_APPLE_TEAM_ALREADY_SETUP';
export const USER_NO_PERMISSIONS_CODE = 'USER_NO_PERMISSIONS';
export const USER_NO_ORGANIZATION_CODE = 'USER_NO_ORGANIZATION';
export const NOT_ENOUGH_PERMISSIONS_CODE = 'NOT_ENOUGH_PERMISSIONS';
export const AT_LEAST_ONE_OWNER_CODE = 'AT_LEAST_ONE_OWNER';
export const AT_LEAST_ONE_ADMIN_CODE = 'AT_LEAST_ONE_ADMIN';
export const USER_ALREADY_EXISTS_CODE = 'USER_ALREADY_EXISTS';
export const APPLICATION_OUTSIDE_ORGANIZATION_CODE =
  'APPLICATION_OUTSIDE_ORGANIZATION';

export const ERROR_TYPE_NOT_FOUND = 'NotFound';
export const APP_NOT_FOUND_CODE = 'APP_NOT_FOUND';
export const ORGANIZATION_NOT_FOUND_CODE = 'ORGANIZATION_NOT_FOUND';
export const USER_NOT_FOUND_CODE = 'USER_NOT_FOUND';
export const LEGAL_DOCUMENT_NOT_FOUND_CODE = 'LEGAL_DOCUMENT_NOT_FOUND';
export const STRIPE_SUBSCRIPTION_NOT_FOUND_CODE =
  'STRIPE_SUBSCRIPTION_NOT_FOUND';
export const STRIPE_CUSTOMER_ID_NOT_FOUND_CODE = 'STRIPE_CUSTOMER_ID_NOT_FOUND';
export const FEATURE_PLAN_NOT_FOUND_CODE = 'FEATURE_PLAN_NOT_FOUND_CODE';

export const ERROR_TYPE_VALIDATION_ERROR = 'ValidationError';
export const MISSING_BODY_CODE = 'MISSING_BODY';
export const MISSING_APPLICATION_CODE = 'MISSING_APPLICATION';
export const MISSING_ORGANIZATION_CODE = 'MISSING_ORGANIZATION';
export const FEATURE_SPECIFICATION_NOT_VALID_CODE =
  'FEATURE_SPECIFICATION_NOT_VALID';
export const INVALID_PLAN_ID_CODE = 'INVALID_PLAN_ID';

export const ERROR_TYPE_ACCESS = 'CannotAccess';
export const SUPERADMIN_PERMISSION_CODE = 'SUPERADMIN_PERMISSION';
export const ORGANIZATION_PERMISSION_CODE = 'ORGANIZATION_PERMISSION';
export const APPLICATION_PERMISSION_CODE = 'APPLICATION_PERMISSION';

export const ERROR_TYPE_INTERNAL_EXCEPTION = 'InternalException';
export const APP_ALREADY_BUILD_CODE = 'APP_ALREADY_BUILD';
export const WORDPRESS_PLAYLISTS_NOT_SET_CODE = 'WORDPRESS_PLAYLISTS_NOT_SET';
export const UNMANAGED_EXCEPTION_CODE = 'UNMANAGED_EXCEPTION';

export const ERROR_TYPE_FORBIDDEN = 'Forbidden';
export const DELETE_OWNER_CODE = 'DELETE_OWNER_CODE';

export const ERROR_TYPE_FOREIGN_API = 'Foreign API';

export const ERROR_TYPE_COMPUTE_ACTIVE_USERS = 'ComputeActiveUsers';
export const CALL_COMPUTE_ACTIVE_USERS_FOR_DAY_CODE =
  'CALL_COMPUTE_ACTIVE_USERS_FOR_DAY';

export const ERROR_TYPE_UNTESTED_CODE = 'UntestedCode';
export const DONT_USE_THIS_CODE = 'DONT_USE_THIS_CODE';
