stages:
  - createRelease
  - prepareDatabase
  - manualMRDeploy
  - lint
  - test
  - incrementVersion
  - push
  # - buildApiDoc
  # - deployApiDoc

variables:
  STAGE: # For the manualMRDeploy step
    description: 'The environment where to deploy'
    value: 'dev'
    options:
      - 'dev'
      - 'preprod'
      - 'prod'
  REGION: # For the manualMRDeploy step
    description: 'The AWS region where to deploy'
    value: 'us-east-1'
    options:
      - 'us-east-1'
      - 'eu-west-3'
  MODULES: # For the manualMRDeploy step
    description: 'The space-separated list of modules to deploy ; when empty, uses the diff with the target branch'
    value: ''

createRelease:
  image: node:16
  stage: createRelease
  allow_failure: true
  before_script:
    - apt update -yq && apt install -yqq openssh-client git
    - eval $(ssh-agent -s)
    - echo "$SSH_BOT_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config --global user.email "bot@crowdaa.com"
    - git config --global user.name "Crowdaa Bot"
  script:
    - SSH_REPOSITORY_URL=$(echo "${CI_REPOSITORY_URL}" | sed -e 's|https\?://gitlab-ci-token:.*@|ssh://git@|g')
    - git remote set-url origin "$SSH_REPOSITORY_URL"
    - git fetch
    - git checkout dev
    - |
      VERSION=$(npm version minor --no-git-tag-version)
      BRANCH_NAME="release/$VERSION"
      while git show-branch "origin/$BRANCH_NAME"; do
        VERSION=$(npm version minor --no-git-tag-version)
        BRANCH_NAME="release/$VERSION"
      done
    - git checkout -- package.json package-lock.json
    - git checkout -b "$BRANCH_NAME"
    - git push -u origin "$BRANCH_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      when: manual

preparePreprodDatabase:
  image: node:16
  stage: prepareDatabase
  variables:
    OPERATION: prod_to_preprod
  allow_failure: true
  before_script:
    - which gpg > /dev/null || apt update -yq && apt install gnupg
    - wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
    - . /etc/os-release # For VERSION_CODENAME. Should be "buster".
    - echo "deb http://repo.mongodb.org/apt/debian $VERSION_CODENAME/mongodb-org/4.4 main" > /etc/apt/sources.list.d/mongodb-org-4.4.list
    - apt update -yq
    - apt install -yqq openssh-client git mongodb-org-tools
    - eval $(ssh-agent -s)
    - echo "$SSH_BOT_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - 'test -f /.dockerenv && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config --global user.email "bot@crowdaa.com"
    - git config --global user.name "Crowdaa Bot"
    - git clone --depth 1 --branch master git@gitlab.aws.crowdaa.com:crowdaa/crowdaa_utils.git crowdaa_utils
    - cd crowdaa_utils/js
    - npm i
    - cd ../..
  script:
    - ./crowdaa_utils/js/bin/cloneDatabase --operation "${OPERATION:-prod_to_preprod}" --drop --tempDir "$PWD/db-clone-temp"
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\/.*/i
      when: manual

manualMRDeploy:
  image: node:16
  stage: manualMRDeploy
  allow_failure: true
  before_script:
    - npm i
    - npm run install
  script:
    - branchName=$(date '+%s')
    - while [ "${#branchName}" -lt 30 ]; do branchName="$branchName$RANDOM"; done
    - branchName="tmp-$branchName"
    - git checkout -b "$branchName"
    - commitsInTargetButNotInHead=$(git log --oneline "$branchName..origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" | wc -l)
    - |
      if [ "$commitsInTargetButNotInHead" -gt 0 ]; then
        echo "Attempting rebase from $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME to origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME ($commitsInTargetButNotInHead extra commits in target branch)"
        git config --global user.email "bot@crowdaa.com"
        git config --global user.name "Crowdaa Bot"
        git rebase origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      fi
    - git diff --dirstat=files,0 "origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" | awk '{ print $2 }' | cut -d'/' -f1 | sort | uniq | grep -v .vscode | grep -v old_modules > diffList || true
    - awk 'NR==FNR{a[$0]=$0;next}a[$0]' diffList deployOrderList > folderList
    - modulesList=$(cat folderList)
    - modulesList="${MODULES:-$modulesList}"
    - ccount=$(echo "$modulesList" | wc -c)
    - if [ "x$modulesList" = "x" ]; then echo "No modules found to deploy!"; exit 1; fi
    - |
      for i in $modulesList; do
        echo "Deploying '$i'"
        cd "$i"
        npx sls deploy --stage "$STAGE" --region "$REGION"
        cd ..
      done
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual

eslint:
  image: node:16
  stage: lint
  before_script:
    - find -mindepth 2 -maxdepth 2 -type f -name 'package.json' | cut -d'/' -f2 | sort | grep -v old_modules > folderList || true
    - npm i
    - npm run install
  script:
    - |
      for i in $(<folderList); do
        if [ $i != buildspec ]; then
          echo "Eslint in $i"
          cd "$i"
          ../node_modules/.bin/eslint . --ext .js --ignore-path .gitignore
          cd ..
        fi
      done
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /^(Wip|Draft):/i
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: ($CI_COMMIT_BRANCH =~ /^release\/.*/ || $CI_COMMIT_BRANCH == "dev") && $CI_COMMIT_TITLE !~ /^Auto-upgrade version to |^Merge branch '(master|release\/.*)' into '?dev'?$/i

test:
  image: node:16
  stage: test
  before_script:
    - npm i
    - npm run install
  script:
    - |
      for i in $(<deployOrderList); do
        echo "Test in $i"
        cd "$i"
        if [ -d ./test ]; then
          npm run test || exit 1
        fi
        cd ..
      done
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: ($CI_COMMIT_BRANCH =~ /^release\/.*/ || $CI_COMMIT_BRANCH == "dev") && $CI_COMMIT_TITLE !~ /^Auto-upgrade version to |^Merge branch '(master|release\/.*)' into '?dev'?$/i

incrementVersion:
  image: node:16
  stage: incrementVersion
  before_script:
    - apt update -yq && apt install -yqq openssh-client git
    - eval $(ssh-agent -s)
    - echo "$SSH_BOT_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config --global user.email "bot@crowdaa.com"
    - git config --global user.name "Crowdaa Bot"
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull
    - |
      case "$CI_COMMIT_TITLE" in
        "Merge branch 'feat/"* |
        "Merge branch 'hotfeat/"* |
        "Merge branch 'release/"*)
          export NEW_VERSION=$(npm version minor --no-git-tag-version);;
        *)
          export NEW_VERSION=$(npm version patch --no-git-tag-version);;
      esac
    - git add package*.json
    - git commit --allow-empty -m "Auto-upgrade version to $NEW_VERSION"
    - SSH_REPOSITORY_URL=$(echo "${CI_REPOSITORY_URL}" | sed -e 's|https\?://gitlab-ci-token:.*@|ssh://git@|g')
    - git remote set-url origin "$SSH_REPOSITORY_URL"
    - git fetch
    - git push origin master
    - git checkout dev
    - git pull
    - git merge --no-ff master
    - git push origin dev
    - |
      releases=$(git branch -a --no-merged origin/master | awk '{ print $1 }' | grep '^remotes/origin/release/' | sed -e 's~^remotes/origin/~~') || true
      if [ -n "$releases" ]; then
        for release in $releases; do
          git checkout "$release"
          git pull
          git merge --no-ff master
          git push origin "$release"
        done
      fi
  artifacts:
    paths:
      - 'package.json'
      - 'package-lock.json'
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE !~ /^Auto-upgrade version to /i

pushDevToAWS:
  image: python:latest
  stage: push
  variables:
    S3_BUCKET_NAME: 'crowdaa-ci/ms/dev/in'
  before_script:
    - apt-get update -qq && apt-get install -y -qq zip
  script:
    - pip install awscli
    - git fetch
    - git diff --dirstat=files,0 origin/dev^ -- . | awk '{ print $2 }' | cut -d'/' -f1 | sort | uniq > diffList
    - awk 'NR==FNR{a[$0]=$0;next}a[$0]' diffList deployOrderList > folderList
    - rm -f diffList
    - if [ "$CI_FORCE_PUSH_TO" = "$CI_COMMIT_BRANCH" ] || grep -qe '^libs$' folderList; then cp deployOrderList folderList; fi
    - find . -type f -exec zip crowdaa-ms-app-source.zip {} +
    - aws s3 cp ./ s3://${S3_BUCKET_NAME}/ --recursive --exclude "*" --include "crowdaa-ms-app-source.zip"
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

pushDevToPreprodAWS:
  image: python:latest
  stage: push
  variables:
    S3_BUCKET_NAME: 'crowdaa-ci-fr/ms/preprod/in'
  before_script:
    - apt-get update -qq && apt-get install -y -qq zip
  script:
    - pip install awscli
    - git fetch
    - cp deployOrderList folderList
    - find . -type f -exec zip crowdaa-ms-app-source.zip {} +
    - aws s3 cp ./ s3://${S3_BUCKET_NAME}/ --recursive --exclude "*" --include "crowdaa-ms-app-source.zip"
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

pushPreprodToAWS:
  image: python:latest
  stage: push
  variables:
    S3_BUCKET_NAME: 'crowdaa-ci-fr/ms/preprod/in'
  before_script:
    - apt-get update -qq && apt-get install -y -qq zip
  script:
    - pip install awscli
    - git fetch
    - git diff --dirstat=files,0 origin/master -- . | awk '{ print $2 }' | cut -d'/' -f1 | sort | uniq > diffList
    - awk 'NR==FNR{a[$0]=$0;next}a[$0]' diffList deployOrderList > folderList
    - rm -f diffList
    - if [ "$CI_FORCE_PUSH_TO" = "$CI_COMMIT_BRANCH" ] || grep -qe '^libs$' folderList; then cp deployOrderList folderList; fi
    - find . -type f -exec zip crowdaa-ms-app-source.zip {} +
    - aws s3 cp ./ s3://${S3_BUCKET_NAME}/ --recursive --exclude "*" --include "crowdaa-ms-app-source.zip"
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\/.*/

pushProdUsToAWS:
  image: python:latest
  stage: push
  variables:
    S3_BUCKET_NAME: 'crowdaa-ci/ms/prod/in'
  before_script:
    - apt-get update -qq && apt-get install -y -qq zip
  script:
    - pip install awscli
    - cp deployOrderList folderList
    - find . -type f -exec zip crowdaa-ms-app-source.zip {} +
    - aws s3 cp ./ s3://${S3_BUCKET_NAME}/ --recursive --exclude "*" --include "crowdaa-ms-app-source.zip"
  rules:
    - if: $CI_COMMIT_TAG =~ /^release-.*/

pushProdFrToAWS:
  image: python:latest
  stage: push
  variables:
    S3_BUCKET_NAME: 'crowdaa-ci-fr/ms/prod/in'
  before_script:
    - apt-get update -qq && apt-get install -y -qq zip
  script:
    - pip install awscli
    - cp deployOrderList folderList
    - find . -type f -exec zip crowdaa-ms-app-source.zip {} +
    - aws s3 cp ./ s3://${S3_BUCKET_NAME}/ --recursive --exclude "*" --include "crowdaa-ms-app-source.zip"
  rules:
    - if: $CI_COMMIT_TAG =~ /^release-.*/
# buildDevApiDoc:
#   image: node:16
#   stage: buildApiDoc
#   before_script:
#     - npm i
#     - npm run install
#   script:
#     - cd swagger
#     - npm run build
#     - cd ..
#   rules:
#     - if: $CI_COMMIT_BRANCH == "dev"
#       changes:
#         - '*/swagger/*'
#         - swagger/**/*
#   artifacts:
#     expire_in: 1 hrs
#     paths:
#       - swagger/dist/

# deployDevApiDoc:
#   image: python:latest
#   stage: deployApiDoc
#   variables:
#     S3_BUCKET_NAME: 'dev-api.crowdaa.com'
#   before_script:
#     - pip install awscli
#   script:
#     - aws s3 cp swagger/dist/ s3://${S3_BUCKET_NAME}/ --recursive
#   dependencies:
#     - buildDevApiDoc
#   rules:
#     - if: $CI_COMMIT_BRANCH == "dev"
#       changes:
#         - '*/swagger/*'
#         - swagger/**/*

# buildPreprodApiDoc:
#   image: node:16
#   stage: buildApiDoc
#   before_script:
#     - npm i
#     - npm run install
#   script:
#     - cd swagger
#     - npm run build:prod
#     - cd ..
#   rules:
#     - if: $CI_COMMIT_BRANCH =~ /^release\/.*/
#       changes:
#         - '*/swagger/*'
#         - swagger/**/*
#   artifacts:
#     expire_in: 1 hrs
#     paths:
#       - swagger/dist/

# deployPreprodApiDoc:
#   image: python:latest
#   stage: deployApiDoc
#   variables:
#     S3_BUCKET_NAME: 'preprod-api.crowdaa.com'
#   before_script:
#     - pip install awscli
#   script:
#     - aws s3 cp swagger/dist/ s3://${S3_BUCKET_NAME}/ --recursive
#   dependencies:
#     - buildPreprodApiDoc
#   rules:
#     - if: $CI_COMMIT_BRANCH =~ /^release\/.*/
#       changes:
#         - '*/swagger/*'
#         - swagger/**/*

# buildProdApiDoc:
#   image: node:16
#   stage: buildApiDoc
#   before_script:
#     - npm i
#     - npm run install
#   script:
#     - cd swagger
#     - npm run build:prod
#     - cd ..
#   rules:
#     - if: $CI_COMMIT_TAG =~ /^release-.*/
#       changes:
#         - '*/swagger/*'
#         - swagger/**/*
#   artifacts:
#     expire_in: 1 hrs
#     paths:
#       - swagger/dist/

# deployProdApiDoc:
#   image: python:latest
#   stage: deployApiDoc
#   variables:
#     S3_BUCKET_NAME: 'api.crowdaa.com'
#   before_script:
#     - pip install awscli
#   script:
#     - aws s3 cp swagger/dist/ s3://${S3_BUCKET_NAME}/ --recursive
#   dependencies:
#     - buildProdApiDoc
#   rules:
#     - if: $CI_COMMIT_TAG =~ /^release-.*/
#       changes:
#         - '*/swagger/*'
#         - swagger/**/*
