service: lineup

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - events:PutRule
      Resource: "*"
    - Effect: Allow
      Action:
        - events:DeleteRule
      Resource: "*"
    - Effect: Allow
      Action:
        - events:PutTargets
      Resource: "*"
    - Effect: Allow
      Action:
        - events:RemoveTargets
      Resource: "*"
    - Effect: Allow
      Action:
        - iam:PassRole
      Resource: arn:aws:iam::*:role/AWS_Events_Invoke_Targets
    - Effect: Allow
      Action: sts:AssumeRole
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:AddPermission
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:RemovePermission
      Resource: "*"
  environment:
    STAGE: ${self:provider.stage}
    REGION:  ${self:provider.region}
    COLL_NAME: lineup
    DB_NAME: crowdaaDev
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}
    BLAST_TEXT: ${self:custom.blast.text.${self:provider.stage}}
    BLAST_NOTIF: ${self:custom.blast.notif.${self:provider.stage}}
    USE_BLAST_TEXT: false
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
    restApiResources:
      /artists/{id}: ${cf:artists-${self:provider.stage}.RestApiRootResourceId}
      /festivals/{id}: ${cf:festivals-${self:provider.stage}.RestApiRootResourceId}
      /stages/{id}: ${cf:stages-${self:provider.stage}.RestApiRootResourceId}
      /users/{id}: ${cf:users-${self:provider.stage}.RestApiRootResourceId}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  notifyLineup:
    handler: handler.handlerNotifyLineup

  postLineup:
    handler: handlers/postLineup.default
    events:
      - http:
          path: lineup/
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true

  createNotifyLineup:
    handler: handler.handlerCreateNotifyLineup
    events:
      - http:
          path: lineup/{id}/notifications
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  createNotifyAllLineup:
    handler: handler.handlerCreateNotifyAllLineup
    events:
      - http:
          path: lineup/notifications
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true

  getPublicLineups:
    handler: handlers/getLineups.default
    events:
      - http:
          path: lineups/
          method: get
          cors: true

  getLineups:
    handler: handler.handleGetLineup
    events:
      - http:
          path: artists/{id}/lineup
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
      - http:
          path: festivals/{id}/lineup
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
      - http:
          path: stages/{id}/lineup
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  getLineup:
    handler: handlers/getLineup.default
    events:
      - http:
          path: lineups/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  getUserLineups:
    handler: handlers/getUserLineups.default
    events:
      - http:
          path: users/{id}/lineups
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  blast:
    text:
      dev: blast-dev-blastText
      prod: blast-prod-blastText
      awax: blast-prod-blastText
    notif:
      dev: blast-dev-blastNotification
      prod: blast-prod-blastNotification
      awax: blast-prod-blastNotification
  webpackIncludeModules: true

resources:
  Outputs:
    RestApiRootResourceId:
      Description: Api Gateway lineup ID
      Value:
        Ref: ApiGatewayResourceLineupIdVar
      Export:
        Name: ${self:service}:${self:provider.stage}:RestApiRootResourceId
