service: userGeneratedContents

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
    restApiResources:
      /press/articles: ${cf:pressArticles-${self:provider.stage}.RestApiRootResourcePressId}
      /press/articles/{id}: ${cf:pressArticles-${self:provider.stage}.RestApiRootResourcePressArticlesId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  postUserGeneratedContents:
    handler: handlers/postUserGeneratedContents.default
    events:
      - http:
          path: press/articles/userGeneratedContents
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          request:
            parameters:
              headers:
                Authorization: true

  getMultipleUserGeneratedContents:
    handler: handlers/getMultipleUserGeneratedContents.default
    events:
      - http:
          path: press/articles/{id}/userGeneratedContents
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          request:
            parameters:
              paths:
                id: true

  patchUserGeneratedContents:
    handler: handlers/patchUserGeneratedContents.default
    events:
      - http:
          path: userGeneratedContents/{id}
          method: patch
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

  removeUserGeneratedContents:
    handler: handlers/removeUserGeneratedContents.default
    events:
      - http:
          path: userGeneratedContents/{id}
          method: delete
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

  getUserGeneratedContents:
    handler: handlers/getUserGeneratedContents.default
    events:
      - http:
          path: userGeneratedContents/{id}
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true
