service: shop

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    COLL_NAME: shopOrders
    REGION: us-east-1
    STAGE: ${self:provider.stage}
    DB_NAME: crowdaaDev
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}

functions:
  getShopItems:
    handler: handler.handleGetShopItems
    events:
      - http:
          path: shop/items
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
  getShopItem:
    handler: handler.handleGetShopItem
    events:
      - http:
          path: shop/items/{id}
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
  postShopOrder:
    handler: handler.handlePostShopOrder
    events:
      - http:
          path: /shop/items/{id}/orders
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true
