service: search

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  createIndex:
    handler: handlers/createIndex.handleCreateIndex
  search:
    handler: handlers/search.handleSearch
    events:
      - http:
          path: search
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              querystrings: ${self:custom.querystrings}

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  IntegrationRequestParameters:
    integration.request.header.x-api-key: method.request.header.x-api-key
    integration.request.querystring.text: method.request.querystring.text
  querystrings:
    text: false
  RequestParameters:
    method.request.header.Authorization: true
    method.request.header.x-api-key: true

resources:
  Resources:
    ApiGatewayMethodSearchGet:
      Properties:
        RequestParameters: ${self:custom.RequestParameters}
        Integration:
          RequestParameters: ${self:custom.IntegrationRequestParameters}
          CacheNamespace: ApiGatewayMethodSearchCacheNS
          CacheKeyParameters:
            - method.request.header.Authorization
            - method.request.header.x-api-key
            - method.request.querystring.text
