version: 0.2

phases:
  pre_build: 
    commands:
      - rm -rf package-lock.json
      - npm i
      - cd libs
      - npm i
      - cd .. 

  build:
    commands:
      - ./deployDiff.sh preprod us-east-1
