version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build: 
    commands:
      - npm i
      - npm run install

  build:
    commands:
      - ./deployDiff.sh dev "$AWS_REGION"
