version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - cd .
      - npm i

  build:
    commands:
      - node --loader=ts-node/esm ./prepare.js dev "$AWS_REGION" verbose,remove
