version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - cd .
      - npm install -g bun
      - bun install
      - bun run install

  build:
    commands:
      # - npm i
      - ./prepare.js dev "$AWS_REGION" verbose,remove
