service: chat

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: "20201221"
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  chatMessageSent:
    handler: handlers/chatMessageSent.default
    events:
      - http:
          path: chat/message/sent
          method: put
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true

  chatUserActivity:
    handler: handlers/chatUserActivity.default
    events:
      - http:
          path: chat/user/activity
          method: put
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true

plugins:
  - serverless-disable-request-validators
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-export-env

custom:
  prune:
    automatic: true
    number: 3
  serverless-disable-request-validators:
    action: delete

package:
  individually: true
