service: auth

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment:
    $<<: 
      - ${file(../env.yml)}
      - ${file(./env.${self:provider.stage}.yml)}

  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, file(../api-v1/serverless.yml):custom.region.${self:provider.stage}, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  appleLogin:
    handler: handlers/appleLogin.default
    events:
      - http:
          path: auth/apple
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  facebookLogin:
    handler: handlers/facebookLogin.default
    events:
      - http:
          path: auth/facebook
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  forgotPassword:
    handler: handlers/forgotPassword.default
    events:
      - http:
          path: auth/forgotPassword
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  login:
    handler: handlers/login.default
    events:
      - http:
          path: auth/login
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  logout:
    handler: handlers/logout.default
    events:
      - http:
          path: auth/facebook/logout
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-User-Id
      - http:
          path: auth/logout
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-User-Id
              - X-Auth-Token

  oidcLogin:
    handler: handlers/oidcLogin.default
    events:
      - http:
          path: auth/oidc
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  register:
    handler: handlers/register.default
    events:
      - http:
          path: auth/register
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  resetPassword:
    handler: handlers/resetPassword.default
    events:
      - http:
          path: auth/resetPassword
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  validateEmail:
    handler: handlers/validateEmail.default
    events:
      - http:
          path: auth/validateEmail
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

plugins:
  - serverless-offline
  - '@cruglobal/serverless-merge-config'
  - serverless-export-env
  - serverless-webpack

package:
  individually: true
