service: festivals

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment:
    COLL_NAME: festivals
    DB_NAME: crowdaaDev
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  getFestivals:
    handler: handlers/getFestivals.handleGetFestivals
    events:
      - http:
          path: festivals
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true

  getFestival:
    handler: handlers/getFestival.handleGetFestival
    events:
      - http:
          path: festivals/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-webpack

package:
  individually: true

resources:
  Outputs:
    RestApiRootResourceId:
      Description: Api Gateway festivals ID
      Value:
        Ref: ApiGatewayResourceFestivalsIdVar
      Export:
        Name: ${self:service}:${self:provider.stage}:RestApiRootResourceId
