service: festivals

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: "20201221"
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  getFestivals:
    handler: handlers/getFestivals.handleGetFestivals
    events:
      - http:
          path: festivals
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true

  getFestival:
    handler: handlers/getFestival.handleGetFestival
    events:
      - http:
          path: festivals/{id}
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

plugins:
  - serverless-disable-request-validators
  - serverless-webpack
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3
  serverless-disable-request-validators:
    action: delete

package:
  individually: true

resources:
  Outputs:
    RestApiRootResourceId:
      Description: Api Gateway festivals ID
      Value:
        Ref: ApiGatewayResourceFestivalsIdVar
      Export:
        Name: ${self:service}:${self:provider.stage}:RestApiRootResourceId
