service: favorites

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    COLL_NAME: artistsFav
    DB_NAME: crowdaaDev
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiResources:
      /artists/{id}: ${cf:artists-${self:provider.stage}.RestApiRootResourceId}

functions:
  manageFavorite:
    handler: handler.handleFavorite
    events:
      - http:
          path: artists/{id}/favorites
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
      - http:
          path: artists/{id}/favorites
          method: delete
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true          
      - http:
          path: artists/{id}/favorites
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true
