service: favorites

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiResources:
      /artists/{id}: ${cf:artists-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  manageFavorite:
    handler: handlers/favorite.default
    events:
      - http:
          path: artists/{id}/favorites
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
      - http:
          path: artists/{id}/favorites
          method: delete
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
      - http:
          path: artists/{id}/favorites
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    includeModules: true
