service: blast

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 60
  environment:
    MAILGUN_API_KEY: ${self:custom.MAILGUN_API_KEY.${self:provider.stage}}
    MAILGUN_DOMAIN: ${self:custom.MAILGUN_DOMAIN.${self:provider.stage}}
    FROM: postmaster
    SNS_ACCESS_KEY_ID: AKIAI3H2I7ZIK4ARL2NA
    SNS_REGION: us-west-2
    SNS_SECRET_ACCESS_KEY: 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
    STAGE: ${self:provider.stage}

functions:
  blastEmail:
    handler: handler.handleBlastEmail
  blastNotification:
    handler: handler.handleBlastNotification
  blastText:
    handler: handler.handleBlastText

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  MAILGUN_API_KEY:
    dev: key-ee8f3c350f56cbe4002b9c00cce04769
    prod: key-ee8f3c350f56cbe4002b9c00cce04769
  MAILGUN_DOMAIN:
    dev: sandboxe8ecbf94ba82415c9ce55b169129af2e.mailgun.org
    prod: mg.crowdaa.com
  webpackIncludeModules: true
