service: blast

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  memorySize: 2048
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    $<<: 
      - ${file(../env.yml)}
      - ${file(./env.${self:provider.stage}.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, file(../api-v1/serverless.yml):custom.region.${self:provider.stage}, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  blastEmail:
    handler: handlers/blastEmail.default
  blastNotification:
    handler: handlers/blastNotif.default
  blastText:
    handler: handlers/blastText.default
  pressBlastNotif:
    handler: handlers/pressBlastNotif.default
  removeBlastToken:
    handler: handlers/removeBlastToken.default

  getBlasts:
    handler: handlers/getBlasts.default
    events:
      - http:
          path: blasts
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true

plugins:
  - serverless-offline
  - '@cruglobal/serverless-merge-config'
  - serverless-webpack

package:
  individually: true
