service: blast

custom:
  prune:
    automatic: true
    number: 3
  serverless-disable-request-validators:
    action: delete
  dev:
    us-east-1:
      NOTIFICATION_STATE_MACHINE_NAME: DevSendNotifications
      NOTIFICATION_STATE_MACHINE_ROLE: arn:aws:iam::630176884077:role/service-role/StepFunctions-DevUsSendNotifications-role
  preprod:
    eu-west-3:
      NOTIFICATION_STATE_MACHINE_NAME: PreprodSendNotifications
      NOTIFICATION_STATE_MACHINE_ROLE: arn:aws:iam::630176884077:role/service-role/StepFunctions-PreprodFrSendNotifications-role
  prod:
    us-east-1:
      NOTIFICATION_STATE_MACHINE_NAME: ProdSendNotifications
      NOTIFICATION_STATE_MACHINE_ROLE: arn:aws:iam::630176884077:role/service-role/StepFunctions-ProdUsSendNotifications-role
    eu-west-3:
      NOTIFICATION_STATE_MACHINE_NAME: ProdSendNotifications
      NOTIFICATION_STATE_MACHINE_ROLE: arn:aws:iam::630176884077:role/service-role/StepFunctions-ProdFrSendNotifications-role

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: '20201221'
  stage: ${opt:stage, "dev"}
  memorySize: 2048
  timeout: 300
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
    - Effect: Allow
      Action:
        - states:CreateStateMachine
        - states:StartExecution
      Resource: 'arn:aws:states:${self:provider.region}:630176884077:stateMachine:${self:custom.${self:provider.stage}.${self:provider.region}.NOTIFICATION_STATE_MACHINE_NAME}'
    - Effect: Allow
      Action:
        - iam:PassRole
      Resource: '${self:custom.${self:provider.stage}.${self:provider.region}.NOTIFICATION_STATE_MACHINE_ROLE}'
    - Effect: Allow
      Action:
        - states:StopExecution
      Resource: 'arn:aws:states:${self:provider.region}:630176884077:execution:${self:custom.${self:provider.stage}.${self:provider.region}.NOTIFICATION_STATE_MACHINE_NAME}:${self:provider.stage}*'
  environment:
    $<<:
      - ${file(../env.yml)}
      - ${file(./env.${self:provider.stage}.${self:provider.region}.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  blastEmail:
    handler: handlers/blastEmail.default
  blastNotification:
    handler: handlers/blastNotif.default
  blastText:
    handler: handlers/blastText.default
  pressBlastNotif:
    handler: handlers/pressBlastNotif.default
  removeBlastToken:
    handler: handlers/removeBlastToken.default

  sendNotifications:
    handler: handlers/sendNotifications.default
  queueNotifications:
    handler: handlers/queueNotifications.default
  unqueueNotifications:
    handler: handlers/unqueueNotifications.default

  getBlasts:
    handler: handlers/getBlasts.default
    events:
      - http:
          path: blasts
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true

  sendBlastUsersPush:
    handler: handlers/sendBlastUsersPush.default
    events:
      - http:
          path: blast/users/push
          method: put
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true

plugins:
  - serverless-disable-request-validators
  - '@cruglobal/serverless-merge-config'
  - serverless-webpack
  - serverless-prune-plugin

package:
  individually: true
