service: api-v1

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: nodejs6.10
  memorySize: 128
  timeout: 30

functions:
  getV1:
    handler: handler.handleGetV1
    events:
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-domain-manager
  - serverless-webpack

package:
  individually: true

custom:
  mongoDB:
    dev: mongodb://crowdaaMS:b0cfc2ffd49b6f27af7ed0cda6a49025@mongodev.aws.crowdaa.com:27017/crowdaaDev
    prod: mongodb://crowdaaMS:9871e59eac27cc669218907c570da230@aws-eu-west-1-portal.10.dblayer.com:18012,aws-eu-west-1-portal.8.dblayer.com:18012/crowdaaDev?ssl=true

  domains:
    prod: api.aws.crowdaa.com
    dev: dev-api.aws.crowdaa.com

  customDomain:
    basePath: "v1"
    domainName: ${self:custom.domains.${self:provider.stage}}
    stage: "${self:provider.stage}"
    createRoute53Record: true

  webpackIncludeModules: true

resources:
  Outputs:
    MongoURL:
      Description: MongoDB URL
      Value: ${self:custom.mongoDB.${self:provider.stage}}
      Export:
        Name: ${self:service}:${self:provider.stage}:MongoURL
    RestApiId:
      Description: Api Gateway ID
      Value: 
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:service}:${self:provider.stage}:RestApiId
    RestApiRootResourceId:
      Description: Api Gateway ID
      Value: {"Fn::GetAtt":["ApiGatewayRestApi","RootResourceId"]}
      Export:
        Name: ${self:service}:${self:provider.stage}:RestApiRootResourceId
