# First deployment :
# - comment MethodSettings, restApiGatewayDeployment and restApiBasePathMapping on first
# - deploy api-v1
# - run deploy script for others MS
# - uncomment previous then re-deploy api-v1
# This should now be done automatically using ./serverless-initial-deploy.yml and new changes in ../gitlab-ci and ../deployDiff.sh

service: api-v1

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: nodejs12.x
  memorySize: 128
  timeout: 30
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  getV1:
    handler: handler.handleGetV1
    events:
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-bind-deployment-id
## uncomment on first deploy --- START1
#  - serverless-domain-manager # See https://github.com/serverless/serverless/issues/4029#issuecomment-386045929
## uncomment on first deploy --- END1
  - serverless-webpack

package:
  individually: true

custom:
  mongoDB:
    dev: mongodb://crowdaaMS:b0cfc2ffd49b6f27af7ed0cda6a49025@mongodev.aws.crowdaa.com:27017/crowdaaDev
    preprod: mongodb://crowdaaMS:b0cfc2ffd49b6f27af7ed0cda6a49025@mongodev.aws.crowdaa.com:27017/crowdaaDev
    prod: mongodb://crowdaaMS:9871e59eac27cc669218907c570da230@crowdaa-shard-00-00-vtd2k.mongodb.net:27017,crowdaa-shard-00-01-vtd2k.mongodb.net:27017,crowdaa-shard-00-02-vtd2k.mongodb.net:27017/crowdaaDev?ssl=true&replicaSet=crowdaa-shard-0&authSource=admin
    defJam: mongodb://crowdaaMS:9871e59eac27cc669218907c570da230@aws-us-west-2-portal.2.dblayer.com:18201,aws-us-west-2-portal.1.dblayer.com:18201/crowdaaDev?ssl=true
    awax: mongodb://crowdaaMS:9871e59eac27cc669218907c570da230@awax-shard-00-00-vtd2k.mongodb.net:27017,awax-shard-00-01-vtd2k.mongodb.net:27017,awax-shard-00-02-vtd2k.mongodb.net:27017/crowdaaDev?ssl=true&replicaSet=awax-shard-0&authSource=admin
    awaxDev: mongodb://crowdaaMS:b0cfc2ffd49b6f27af7ed0cda6a49025@mongodevawax.aws.crowdaa.com:27017/crowdaaDev

  domains:
    prod: api.aws.crowdaa.com
    preprod: preprod-api.aws.crowdaa.com
    dev: dev-api.aws.crowdaa.com
    defJam: defjam-api.aws.crowdaa.com
    awax: awax-api.aws.crowdaa.com
    awaxDev: awax-dev-api.aws.crowdaa.com

  adminApp:
    prod: cf72c7c3-ae67-42f9-963c-adc9a3211726
    preprod: crowdaa_app_id
    dev: crowdaa_app_id
    defJam: crowdaa_app_id
    awax: cf72c7c3-ae67-42f9-963c-adc9a3211726
    awaxDev: crowdaa_app_id

  customDomain:
    basePath: "v1"
    domainName: ${self:custom.domains.${self:provider.stage}}
    endpointType: "regional"
    stage: "${self:provider.stage}"
    createRoute53Record: true

  MAILGUN_API_KEY:
    dev: key-ee8f3c350f56cbe4002b9c00cce04769
    preprod: key-ee8f3c350f56cbe4002b9c00cce04769
    prod: key-ee8f3c350f56cbe4002b9c00cce04769
    awax: key-ee8f3c350f56cbe4002b9c00cce04769
    awaxDev: key-ee8f3c350f56cbe4002b9c00cce04769

  MAILGUN_DOMAIN:
    dev: mg.crowdaa.com
    preprod: mg.crowdaa.com
    prod: mg.crowdaa.com
    awax: mg.crowdaa.com
    awaxDev: mg.crowdaa.com

resources:
  Resources:
    ApiGatewayStage:
      Type: "AWS::ApiGateway::Stage"
      Properties:
        StageName: ${self:provider.stage}
        Description: "stage of api-v1"
        RestApiId:
          Ref: "ApiGatewayRestApi"
        DeploymentId:
          Ref: __deployment__
        CacheClusterEnabled: true
        CacheClusterSize: "0.5"
# remove on first deploy --- START1
        MethodSettings:
          - ResourcePath: "/*"
            CachingEnabled: false
            HttpMethod: "*"
            LoggingLevel: "INFO"
            MetricsEnabled: true
          - ResourcePath: "/apps/settings"
            CacheTtlInSeconds: 3600
            CachingEnabled: true
            HttpMethod: "GET"
            LoggingLevel: "INFO"
            MetricsEnabled: true
          - ResourcePath: "/artists/{id}"
            CacheTtlInSeconds: 3600
            CachingEnabled: true
            HttpMethod: "GET"
            LoggingLevel: "INFO"
            MetricsEnabled: true
          - ResourcePath: "/audios/{id}"
            CacheTtlInSeconds: 3600
            CachingEnabled: true
            HttpMethod: "GET"
            LoggingLevel: "INFO"
            MetricsEnabled: true
          - ResourcePath: "/crowd"
            CacheDataEncrypted: true
            CacheTtlInSeconds: 3600
            CachingEnabled: true
            HttpMethod: "GET"
            LoggingLevel: "INFO"
            MetricsEnabled: true
          - ResourcePath: "/selections"
            CacheTtlInSeconds: 3600
            CachingEnabled: true
            HttpMethod: "GET"
            LoggingLevel: "INFO"
            MetricsEnabled: true
          - ResourcePath: "/selections/{id}"
            CacheTtlInSeconds: 3600
            CachingEnabled: true
            HttpMethod: "GET"
            LoggingLevel: "INFO"
            MetricsEnabled: true
    restApiGatewayDeployment:
      Type: "AWS::ApiGateway::Deployment"
      DependsOn: ApiGatewayMethodGet
      Properties:
        Description: ${self:provider.stage} Environment
        RestApiId:
          Ref: ApiGatewayRestApi
        StageName: ${self:provider.stage}
    # restApiBasePathMapping:
    #   Type: AWS::ApiGateway::BasePathMapping
    #   DependsOn: restApiGatewayDeployment
    #   Properties:
    #     BasePath: "v1"
    #     DomainName: ${self:custom.domains.${self:provider.stage}}
    #     RestApiId:
    #       Ref: ApiGatewayRestApi
    #     Stage: ${self:provider.stage}
# remove  when first deploy --- END1

  Outputs:
    ApiGatewayStage:
      Description: Api Gateway Stage
      Value:
        Ref: ApiGatewayStage
      Export:
        Name: ${self:service}:${self:provider.stage}:ApiGatewayStage
    MongoURL:
      Description: MongoDB URL
      Value: ${self:custom.mongoDB.${self:provider.stage}}
      Export:
        Name: ${self:service}:${self:provider.stage}:MongoURL
    AdminApp:
      Description: Admin App ID
      Value: ${self:custom.adminApp.${self:provider.stage}}
      Export:
        Name: ${self:service}:${self:provider.stage}:AdminApp
    MailgunApiKey:
      Description: MAILGUN API KEY
      Value: ${self:custom.MAILGUN_API_KEY.${self:provider.stage}}
      Export:
        Name: ${self:service}:${self:provider.stage}:MailgunApiKey
    MailgunDomain:
      Description: MAILGUN DOMAIN
      Value: ${self:custom.MAILGUN_DOMAIN.${self:provider.stage}}
      Export:
        Name: ${self:service}:${self:provider.stage}:MailgunDomain
    RestApiId:
      Description: Api Gateway ID
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:service}:${self:provider.stage}:RestApiId
    RestApiRootResourceId:
      Description: Api Gateway ID
      Value: { "Fn::GetAtt": ["ApiGatewayRestApi", "RootResourceId"] }
      Export:
        Name: ${self:service}:${self:provider.stage}:RestApiRootResourceId
