service: carts

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment:
    DB_NAME: crowdaaDev
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}
    STAGE: ${self:provider.stage}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  createCart:
    handler: handlers/createCart.default
    events:
      - http:
          path: carts
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}

  getCart:
    handler: handlers/getCart.default
    events:
      - http:
          path: carts/{id}
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true
