service: selections

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
    restApiResources:
      users/{id}: ${cf:users-${self:provider.stage}.RestApiRootResourceId}

functions:
  getSelection:
    handler: handler.handleGetSelection
    events:
      - http:
          path: selections/{id}
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          cors:
            origin: "*"
            headers:
              - Cache-Control
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              paths:
                id: true

  getSelectionSubscriptions:
    handler: handler.handleGetSelectionSubscriptions
    events:
      - http:
          path: selections/{id}/subscriptions
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  getSelections:
    handler: handler.handleGetSelections
    events:
      - http:
          path: selections
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          cors:
            origin: "*"
            headers:
              - Cache-Control
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              querystrings:
                mobile: false
                root: false
                type: false
                web: false

  getUserSelections:
    handler: handler.handleGetUserSelections
    events:
      - http:
          path: users/{id}/selections
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors:
            origin: "*"
            headers:
              - Cache-Control
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          request:
            parameters:
              paths:
                id: true

  postUserSelection:
    handler: handler.handlePostUserSelection
    events:
      - http:
          path: users/{id}/selections
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  deleteUserSelection:
    handler: handler.handleDeleteUserSelection
    events:
      - http:
          path: users/{id}/selections/{selectionId}
          method: delete
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
                selectionId: true

  patchUserSelection:
    handler: handler.handlePatchUserSelection
    events:
      - http:
          path: users/{id}/selections/{selectionId}
          method: patch
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
                selectionId: true

  linkMediaToSelection:
    handler: handler.handleLinkMediaToSelection
    events:
      - http:
          path: /selections/{id}/media
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  unlinkMediaFromSelection:
    handler: handler.handleUnlinkMediaFromSelection
    events:
      - http:
          path: /selections/{id}/media
          method: delete
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-webpack

package:
  individually: true

resources:
  Resources:
    ApiGatewayMethodSelectionsGet:
      Properties:
        RequestParameters:
          method.request.querystring.mobile: true
          method.request.querystring.root: true
          method.request.querystring.type: true
          method.request.querystring.web: true
        Integration:
          RequestParameters:
            integration.request.querystring.mobile: method.request.querystring.mobile
            integration.request.querystring.root: method.request.querystring.root
            integration.request.querystring.type: method.request.querystring.type
            integration.request.querystring.web: method.request.querystring.web
          CacheNamespace: ApiGatewayMethodSelectionsGetCacheNS
          CacheKeyParameters:
            - method.request.querystring.mobile
            - method.request.querystring.root
            - method.request.querystring.type
            - method.request.querystring.web

    ApiGatewayMethodSelectionsIdVarGet:
      Properties:
        RequestParameters:
          method.request.path.id: true
        Integration:
          RequestParameters:
            integration.request.path.id: method.request.path.id
          CacheNamespace: ApiGatewayMethodSelectionsIdVarGetCacheNS
          CacheKeyParameters:
            - method.request.path.id
