service: selections

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  iamRoleStatements:
   - Effect: Allow
     Action:
       - lambda:InvokeFunction
     Resource: "*"
  environment:
    REGION: us-east-1
    STAGE: ${self:provider.stage}
    COLL_NAME: selection
    DB_NAME: crowdaaDev
    DEFAULT_LIMIT: 15
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}
    USER_SUBS_COLL_NAME: userSubscriptions
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
    restApiResources:
      users/{id}: ${cf:users-${self:provider.stage}.RestApiRootResourceId}

functions:
  getSelection:
    handler: handler.handleGetSelection
    events:
      - http:
          path: selections/{id}
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  getSelections:
    handler: handler.handleGetSelections
    events:
      - http:
          path: selections
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              querystrings:
                type: false
                web: false
                mobile: false

  getUserSelections:
    handler: handler.handleGetUserSelections
    events:
      - http:
          path: users/{id}/selections
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  postUserSelection:
    handler: handler.handlePostUserSelection
    events:
      - http:
          path: users/{id}/selections
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  deleteUserSelection:
    handler: handler.handleDeleteUserSelection
    events:
      - http:
          path: users/{id}/selections/{selectionId}
          method: delete
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
                selectionId: true

  patchUserSelection:
    handler: handler.handlePatchUserSelection
    events:
      - http:
          path: users/{id}/selections/{selectionId}
          method: patch
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
                selectionId: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true

resources:
  Resources:
    ApiGatewayMethodSelectionsGet:
      Properties:
        RequestParameters:
          method.request.querystring.isMobilePublished: true
          method.request.querystring.isRoot: true
          method.request.querystring.isWebPublished: true
          method.request.querystring.selectionCollection: true
        Integration:
          RequestParameters:
            integration.request.querystring.isMobilePublished: method.request.querystring.isMobilePublished
            integration.request.querystring.isRoot: method.request.querystring.isRoot
            integration.request.querystring.isWebPublished: method.request.querystring.isWebPublished
            integration.request.querystring.selectionCollection: method.request.querystring.selectionCollection
          CacheNamespace: ApiGatewayMethodSelectionsGetCacheNS
          CacheKeyParameters:
            - method.request.querystring.isMobilePublished
            - method.request.querystring.isRoot
            - method.request.querystring.isWebPublished
            - method.request.querystring.selectionCollection

    ApiGatewayMethodSelectionsIdVarGet:
      Properties:
        RequestParameters:
          method.request.path.id: true
        Integration:
          RequestParameters:
            integration.request.path.id: method.request.path.id
          CacheNamespace: ApiGatewayMethodSelectionsIdVarGetCacheNS
          CacheKeyParameters:
            - method.request.path.id
