service: userMetrics

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: "20201221"
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  postUserMetrics:
    handler: handlers/postUserMetrics.default
    events:
      - http:
          path: userMetrics
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          request:
            parameters:
              headers:
                Authorization: true

  getAllUserMetrics:
    handler: handlers/getAllUserMetrics.default
    events:
      - http:
          path: userMetrics
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  getUserMetrics:
    handler: handlers/getUserMetrics.default
    events:
      - http:
          path: userMetrics/{id}
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          request:
            parameters:
              paths:
                id: true

  identifyUserMetrics:
    handler: handlers/identifyUserMetrics.default
    events:
      - http:
          path: userMetrics/identify/{id}
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-disable-request-validators
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-export-env

custom:
  prune:
    automatic: true
    number: 3
  serverless-disable-request-validators:
    action: delete

package:
  individually: true

