service: account

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment:
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}

functions:
  authorize:
    handler: handler.handleAuthorize
  authorizeAdmin:
    handler: handler.handleAuthorizeAdmin

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true

resources:
  Resources:
    ApiGatewayAuthorizer: 
      Type: AWS::ApiGateway::Authorizer
      Properties: 
        AuthorizerResultTtlInSeconds: 0
        AuthorizerUri : {
          "Fn::Join": [
            "",
            [
              "arn:aws:apigateway:",
              {"Ref":"AWS::Region"},
              ":lambda:path/2015-03-31/functions/",
              { "Fn::GetAtt": ["AuthorizeLambdaFunction", "Arn" ] },
              "/invocations"
            ]
          ]
        }
        IdentitySource: method.request.header.Authorization
        Name: authorizeAuthorizer
        RestApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
        Type: TOKEN
        ProviderARNs: 
          - { "Fn::GetAtt": ["AuthorizeLambdaFunction", "Arn" ] }
    
    LambdaPermissionApiGateway:
      Type: 'AWS::Lambda::Permission'
      Properties:
        FunctionName: 
          Fn::GetAtt: 
            - AuthorizeLambdaFunction
            - Arn
        Action: 'lambda:InvokeFunction'
        Principal: 
          Fn::Join:
            - ''
            - 
              - apigateway.
              - Ref: 'AWS::URLSuffix'
    
    ApiGatewayResponseDenied:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"
        ResponseTemplates:
          application/json: '{"message":"forbidden"}'
        ResponseType: ACCESS_DENIED
        RestApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
        StatusCode: "403"

    ApiGatewayAuthorizerAdmin: 
      Type: AWS::ApiGateway::Authorizer
      Properties: 
        AuthorizerResultTtlInSeconds: 300
        AuthorizerUri : {
          "Fn::Join": [
            "",
            [
              "arn:aws:apigateway:",
              {"Ref":"AWS::Region"},
              ":lambda:path/2015-03-31/functions/",
              { "Fn::GetAtt": ["AuthorizeAdminLambdaFunction", "Arn" ] },
              "/invocations"
            ]
          ]
        }
        IdentitySource: method.request.header.Authorization
        Name: authorizeAdminAuthorizer
        RestApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
        Type: TOKEN
        ProviderARNs: 
          - { "Fn::GetAtt": ["AuthorizeAdminLambdaFunction", "Arn" ] }

  Outputs:
    ApiGatewayAuthorizerId:
      Description: User authorizer ID
      Value: 
        Ref: ApiGatewayAuthorizer
      Export:
        Name: ${self:service}:${self:provider.stage}:ApiGatewayAuthorizerId
    ApiGatewayAuthorizerAdminId:
      Description: Admin authorizer ID
      Value:
        Ref: ApiGatewayAuthorizerAdmin
      Export:
        Name: ${self:service}:${self:provider.stage}:ApiGatewayAuthorizerAdminId
