service: credits

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment:
    COLL_NAME: credits
    DB_NAME: crowdaaDev
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}

functions:
  getCredits:
    handler: handler.handleGetCredits
    events:
      - http:
          path: credits/
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true

  addCredits:
    handler: handler.handleAddCredits
  
  removeCredits:
    handler: handler.handleRemoveCredits

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true

resources:
  Resources:
    ApiGatewayMethodCreditsGet:
      Properties:
        RequestParameters:
          method.request.header.Authorization: true
        Integration:
          CacheNamespace: ApiGatewayMethodCreditsGetCacheNS
          CacheKeyParameters:
            - method.request.header.Authorization
