service: scanners

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment:
    $<<:
      - ${file(../env.yml)}
      - ${file(./env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
    restApiResources:
      lineup/{id}: ${cf:lineup-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  createScanners:
    handler: handlers/createScanners.default
    events:
      - http:
          path: lineup/{id}/scanners
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true
  getScannersForLineup:
    handler: handlers/getScannersForLineup.default
    events:
      - http:
          path: lineup/{id}/scanners
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true
  getScanner:
    handler: handlers/getScanner.default
    events:
      - http:
          path: scanners/{id}
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          cors: true
          request:
            parameters:
              paths:
                id: true
  patchScanners:
    handler: handlers/patchScanner.default
    events:
      - http:
          path: scanners/{id}
          method: patch
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true
  deleteScanners:
    handler: handlers/deleteScanner.default
    events:
      - http:
          path: scanners/{id}
          method: delete
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

plugins:
  - '@cruglobal/serverless-merge-config'
  - serverless-webpack

package:
  individually: true

custom:
  MAILGUN_API_KEY:
    dev: key-ee8f3c350f56cbe4002b9c00cce04769
    prod: key-ee8f3c350f56cbe4002b9c00cce04769
    awax: key-ee8f3c350f56cbe4002b9c00cce04769
  MAILGUN_DOMAIN:
    dev: mg.crowdaa.com
    prod: mg.crowdaa.com
    awax: mg.crowdaa.com
