service: tickets

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
    restApiResources:
      lineup/{id}: ${cf:lineup-${self:provider.stage}.RestApiRootResourceId}
      users/{id}: ${cf:users-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  getTickets:
    handler: handlers/getTickets.default
    events:
      - http:
          path: users/{id}/tickets
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  buyTickets:
    handler: handlers/buyTickets.default
    events:
      - http:
          path: tickets
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true

  getTicketCategoriesByLineup:
    handler: handlers/getTicketCategoriesByLineup.default
    events:
      - http:
          path: lineup/{id}/ticketCategories
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          request:
            parameters:
              paths:
                id: true

      - http:
          path: users/{id}/lineup/{lineupId}/ticketCategories
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              paths:
                lineupId: true
                id: true
              headers:
                Authorization: true

  postTicketCategoriesByLineup:
    handler: handlers/postTicketCategories.default
    events:
      - http:
          path: lineup/{id}/ticketCategories
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  scanTicket:
    handler: handlers/scanTicket.default
    events:
      - http:
          path: tickets/{id}
          method: patch
          cors: true
          request:
            parameters:
              paths:
                id: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  resendTicket:
    handler: handlers/resendTicket.default
    events:
      - http:
          path: tickets/{id}/resend
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  getTicketCategory:
    handler: handlers/getTicketCategory.default
    events:
      - http:
          path: ticketCategories/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

plugins:
  - serverless-offline
  - serverless-webpack

package:
  individually: true

custom:
  MAILGUN_API_KEY:
    dev: key-ee8f3c350f56cbe4002b9c00cce04769
    preprod: key-ee8f3c350f56cbe4002b9c00cce04769
    prod: key-ee8f3c350f56cbe4002b9c00cce04769
    awax: key-ee8f3c350f56cbe4002b9c00cce04769
  MAILGUN_DOMAIN:
    dev: mg.crowdaa.com
    preprod: mg.crowdaa.com
    prod: mg.crowdaa.com
    awax: mg.crowdaa.com
