service: ssr

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: '20201221'
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment:
    $<<:
      - ${file(../env.yml)}
      - ${file(./env.${self:provider.stage}.${self:provider.region}.yml)}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  article:
    handler: handlers/article.default
    events:
      - http:
          path: /articles/{id}
          method: get
          request:
            parameters:
              querystrings:
                redirect_url: false
                appName: false

  userArticle:
    handler: handlers/userArticle.default
    events:
      - http:
          path: /userArticles/{id}
          method: get
          request:
            parameters:
              querystrings:
                redirect_url: false
                appName: false

plugins:
  - serverless-disable-request-validators
  - '@cruglobal/serverless-merge-config'
  - serverless-domain-manager
  - serverless-export-env
  - serverless-webpack
  - serverless-prune-plugin

package:
  individually: true

custom:
  prune:
    automatic: true
    number: 3
  serverless-disable-request-validators:
    action: delete
  domains:
    dev:
      us-east-1: dev-ssr.aws.crowdaa.com
    preprod:
      eu-west-3: preprod-ssr.aws.crowdaa.com
    prod:
      us-east-1: ssr.aws.crowdaa.com
      eu-west-3: ssr-fr.aws.crowdaa.com

  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}.${self:provider.region}}
    stage: '${self:provider.stage}'
    createRoute53Record: true
