service: ssr

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment: ${file(../env.yml)}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  ticket:
    handler: handlers/ticket.handleArtist
    events:
      - http:
          path: /ticket/artists/{id}
          method: get
          request:
            parameters:
              querystrings:
                redirect_url: false
  
  selection:
    handler: handlers/selection.default
    events:
      - http:
          path: /selections/{id}
          method: get
          request:
            parameters:
              querystrings:
                redirect_url: false

plugins:
  - serverless-domain-manager
  - serverless-webpack

package:
  individually: true

custom:
  domains:
    dev: ssr-dev.aws.crowdaa.com
    prod: ssr.aws.crowdaa.com

  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    stage: '${self:provider.stage}'
    createRoute53Record: true
