service: users

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  addAppId:
    handler: handlers/addAppId.default
    events:
      - http:
          path: users/addAppId
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true

  blastEmail:
    handler: handlers/blastEmail.default
    events:
      - http:
          path: users/{id}/blast/email
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  blastNotification:
    handler: handlers/blastNotification.default
    events:
      - http:
          path: users/{id}/blast/notification
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  blastText:
    handler: handlers/blastText.default
    events:
      - http:
          path: users/{id}/blast/text
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  getProfile:
    handler: handlers/getProfile.default
    events:
      - http:
          path: users/{id}/profile
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  getBalances:
    handler: handlers/getBalances.default
    events:
      - http:
          path: users/{id}/balances
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  getPayouts:
    handler: handlers/getPayouts.default
    events:
      - http:
          path: users/{id}/payouts
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  getUser:
    handler: handlers/getUser.default

  getUserPublic:
    handler: handlers/getUserPublic.default
    events:
      - http:
          path: users/{id}
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerNoAppId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  getHistory:
    handler: handlers/getHistory.default
    events:
      - http:
          path: users/{id}/history/
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  addHistory:
    handler: handlers/addHistory.default
    events:
      - http:
          path: users/{id}/history/
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  optIn:
    handler: handlers/optIn.default
    events:
      - http:
          path: users/{id}/optin
          method: put
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  isBlastable:
    handler: handlers/isBlastable.default
    events:
      - http:
          path: users/{id}/isBlastable
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  addPayout:
    handler: handlers/addPayout.default
    events:
      - http:
          path: users/{id}/payouts
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  sendPinCode:
    handler: handlers/sendPinCode.default
    events:
      - http:
          path: users/{id}/phone
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
  checkPinCode:
    handler: handlers/checkPinCode.default
    events:
      - http:
          path: users/{id}/phone/validation
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  generateApiToken:
    handler: handlers/generateApiToken.default
    events:
      - http:
          path: users/{id}/apiToken
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerRoleId}
          cors: true
          request:
            parameters:
              paths:
                id: true

  editProfile:
    handler: handlers/editProfile.default
    events:
      - http:
          path: users/{id}
          method: put
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerRoleId}
          cors: true
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-webpack
  - serverless-export-env

package:
  individually: true

custom:
  webpackIncludeModules: true

resources:
  Outputs:
    RestApiRootResourceId:
      Description: Api Gateway users ID
      Value:
        Ref: ApiGatewayResourceUsersIdVar
      Export:
        Name: ${self:service}:${self:provider.stage}:RestApiRootResourceId
