service: contacts

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment:
    AWS_KEY: AKIAJGROD5HF6C67HFHA
    AWS_SECRET: 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
    COLL_NAME: ${self:service}
    DB_NAME: crowdaaDev
    LIMIT_DEFAULT: '10'
    LIMIT_MAX: '100'
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  deleteContact:
    handler: handler.handleDeleteContact
    events:
      - http:
          path: contacts/{id}
          method: delete
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

  getContacts:
    handler: handler.handleGetContacts
    events:
      - http:
          path: contacts/
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              querystrings:
                filter: false
                idsOnly: false
                limit: false
                search: false
                skip: false
                sortBy: false
                sortOrder: false
                type: false
  # import:
  #   handler: handler.handleImport
  #   events:
  #     - http: POST contacts/import

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true

resources:
  Resources:
    ApiGatewayMethodContactsGet:
      Properties:
        RequestParameters:
          method.request.header.Authorization: true
          method.request.querystring.filter: false
          method.request.querystring.idsOnly: false
          method.request.querystring.limit: false
          method.request.querystring.search: false
          method.request.querystring.skip: false
          method.request.querystring.sortBy: false
          method.request.querystring.sortOrder: false
          method.request.querystring.type: false
        Integration:
          RequestParameters:
            integration.request.querystring.filter: method.request.querystring.filter
            integration.request.querystring.idsOnly: method.request.querystring.idsOnly
            integration.request.querystring.limit: method.request.querystring.limit
            integration.request.querystring.search: method.request.querystring.search
            integration.request.querystring.skip: method.request.querystring.skip
            integration.request.querystring.sortBy: method.request.querystring.sortBy
            integration.request.querystring.sortOrder: method.request.querystring.sortOrder
            integration.request.querystring.type: method.request.querystring.type
          CacheNamespace: ApiGatewayMethodContactsGetCacheNS
          CacheKeyParameters:
            - method.request.header.Authorization
            - method.request.querystring.filter
            - method.request.querystring.idsOnly
            - method.request.querystring.limit
            - method.request.querystring.search
            - method.request.querystring.skip
            - method.request.querystring.sortBy
            - method.request.querystring.sortOrder
            - method.request.querystring.type
