version: "2"

services:
  deploy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/microservices
    working_dir: /microservices/files
    environment:
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "STAGE=dev"
      - "REGION=${REGION}"
    command: >
      sh -c '
      serverless deploy --stage $${STAGE} --region $${REGION:=us-east-1};
      '