service: files

package:
  exclude:
    - .git/**
    - docker-compose.yml
    - Dockerfile
    - package.json
    - package-lock.json
    - README.md

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, "dev"}
  memorySize: 1536
  timeout: 30
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: 'arn:aws:s3:::${self:provider.environment.S3_UPLOAD_BUCKET}/*'
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: 'arn:aws:s3:::${self:provider.environment.S3_PICTURES_BUCKET}/*'
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: 'arn:aws:s3:::${self:provider.environment.S3_VIDEOS_BUCKET}/*'
    - Effect: Allow
      Action:
        - 's3:GetObject'
        - 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::${self:provider.environment.S3_RESOURCES_BUCKET}/*'
        - 'arn:aws:s3:::${self:provider.environment.S3_PUBLIC_RESOURCES_BUCKET}/*'
    - Effect: 'Allow'
      Action:
        - elastictranscoder:CreateJob
      Resource: '*'
  environment:
    $<<:
      - ${file(../env.yml)}
      - ${file(./env.${self:provider.stage}.${self:provider.region}.yml)}
    S3_UPLOAD_BUCKET: ${file(./env.${self:provider.stage}.${self:provider.region}.yml):S3_UPLOAD_BUCKET}
    S3_PICTURES_BUCKET: ${file(./env.${self:provider.stage}.${self:provider.region}.yml):S3_PICTURES_BUCKET}
    S3_VIDEOS_BUCKET: ${file(./env.${self:provider.stage}.${self:provider.region}.yml):S3_VIDEOS_BUCKET}
    S3_RESOURCES_BUCKET: ${file(./env.${self:provider.stage}.${self:provider.region}.yml):S3_RESOURCES_BUCKET}
    S3_PUBLIC_RESOURCES_BUCKET: ${file(./env.${self:provider.stage}.${self:provider.region}.yml):S3_PUBLIC_RESOURCES_BUCKET}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  getUploadUrl:
    handler: handlers/getUploadUrl.default
    events:
      - http:
          path: files
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true

  deleteFile:
    handler: handlers/deleteFile.default
    events:
      - http:
          path: files
          method: delete
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true

  getSupportedFileFormats:
    handler: handlers/getSupportedFileFormats.default
    events:
      - http:
          path: files/formats
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          cors: true

  onFileCreated:
    handler: handlers/onFileCreated.default
    timeout: 600 # timeout set to 10 minutes for image/video encoding
    events:
      - s3:
          bucket: ${self:provider.environment.S3_UPLOAD_BUCKET}
          event: s3:ObjectCreated:*
          existing: true

  onVideoEncoded:
    handler: handlers/onVideoEncoded.default
    events:
      - sns: video-stream-${self:provider.stage}

  onVideoEncodeError:
    handler: handlers/onVideoEncodeError.default
    events:
      - sns: video-stream-${self:provider.stage}-error

  getResourcesUrls:
    handler: handlers/getResourcesUrls.default
    events:
      - http:
          path: files/resources/{action}
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          cors: true
          request:
            parameters:
              headers:
                Authorization: true

plugins:
  - serverless-disable-request-validators
  - '@cruglobal/serverless-merge-config'
  - serverless-export-env
  - serverless-webpack
  - serverless-prune-plugin

# sharp package need to be include to work properly
custom:
  prune:
    automatic: true
    number: 3
  serverless-disable-request-validators:
    action: delete
  webpack:
    includeModules:
      forceInclude:
        - sharp
