service: apps

custom:
  prune:
    automatic: true
    number: 3
  serverless-disable-request-validators:
    action: delete
  dev:
    us-east-1:
      INVITE_MAIL_LANG: en
      REACT_APP_AUTH_URL: https://dev-auth.crowdaa.com
      REACT_APP_PRESS_SERVICE_URL: https://dev-blog.crowdaa.com
  preprod:
    eu-west-3:
      INVITE_MAIL_LANG: fr
      REACT_APP_AUTH_URL: https://depreprodv-auth.crowdaa.com
      REACT_APP_PRESS_SERVICE_URL: https://preprod-blog.crowdaa.com
  prod:
    us-east-1:
      INVITE_MAIL_LANG: en
      REACT_APP_AUTH_URL: https://auth.crowdaa.com
      REACT_APP_PRESS_SERVICE_URL: https://blog.crowdaa.com
    eu-west-3:
      INVITE_MAIL_LANG: fr
      REACT_APP_AUTH_URL: https://auth-fr.crowdaa.com
      REACT_APP_PRESS_SERVICE_URL: https://blog-fr.crowdaa.com

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: "20201221"
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment:
    $<<:
      ${file(../env.yml)}
    INVITE_MAIL_LANG: '${self:custom.${self:provider.stage}.${self:provider.region}.INVITE_MAIL_LANG}'
    REACT_APP_AUTH_URL: '${self:custom.${self:provider.stage}.${self:provider.region}.REACT_APP_AUTH_URL}'
    REACT_APP_PRESS_SERVICE_URL: '${self:custom.${self:provider.stage}.${self:provider.region}.REACT_APP_PRESS_SERVICE_URL}'
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  getAppPerms:
    handler: handlers/getAppPerms.default
    events:
      - http:
          path: apps/perms
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  getAppSettings:
    handler: handlers/getAppSettings.default
    events:
      - http:
          path: apps/settings
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  getAppAllSettings:
    handler: handlers/getAppAllSettings.default
    events:
      - http:
          path: apps/{id}/settings
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  updateAppAllSettings:
    handler: handlers/updateAppAllSettings.default
    events:
      - http:
          path: apps/{id}/settings
          method: patch
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  inviteAppAdmin:
    handler: handlers/inviteAppAdmin.default
    events:
      - http:
          path: apps/{id}/admins
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  getAppAdmins:
    handler: handlers/getAppAdmins.default
    events:
      - http:
          path: apps/{id}/admins
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  deleteAppAdmin:
    handler: handlers/deleteAppAdmin.default
    events:
      - http:
          path: apps/{id}/admins
          method: delete
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  getAppStatus:
    handler: handlers/getAppStatus.default
    events:
      - http:
          path: apps/{id}/status
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  getAppInfos:
    handler: handlers/getAppInfos.default
    events:
      - http:
          path: apps/{id}/infos
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  getAppBuilds:
    handler: handlers/getAppBuilds.default
    events:
      - http:
          path: apps/{id}/builds
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  getAppPreview:
    handler: handlers/getAppPreview.default
    events:
      - http:
          path: apps/preview/{id}
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          request:
            parameters:
              paths:
                id: true

  sendPreviewInfo:
    handler: handlers/sendPreviewInfo.default
    events:
      - http:
          path: apps/preview
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true

  getAppModals:
      handler: handlers/getAppModals.default
      events:
        - http:
            path: apps/modals
            method: get
            cors: true
            authorizer:
              type: CUSTOM
              authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          request:
            parameters:
              headers:
                Authorization: true

  getAppTos:
      handler: handlers/getAppTos.default
      events:
        - http:
            path: apps/{id}/tos
            method: get
            cors: true
            request:
              parameters:
                paths:
                  id: true

plugins:
  - serverless-disable-request-validators
  - '@cruglobal/serverless-merge-config'
  - serverless-webpack
  - serverless-prune-plugin

resources:
  Resources:
    ApiGatewayMethodAppsSettingsGet:
      Properties:
        RequestParameters:
          method.request.header.x-api-key: true
        Integration:
          RequestParameters:
            integration.request.header.x-api-key: method.request.header.x-api-key
          CacheNamespace: ApiGatewayMethodAppsSettingsGetCacheNS
          CacheKeyParameters:
            - method.request.header.x-api-key
