service: apps

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  getAppSettings:
    handler: handlers/getAppSettings.default
    events:
      - http:
          path: apps/settings
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  getAppInfos:
    handler: handlers/getAppInfos.default
    events:
      - http:
          path: apps/{id}/infos
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerNoAppId}
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true

resources:
  Resources:
    ApiGatewayMethodAppsSettingsGet:
      Properties:
        RequestParameters:
          method.request.header.x-api-key: true
        Integration:
          RequestParameters:
            integration.request.header.x-api-key: method.request.header.x-api-key
          CacheNamespace: ApiGatewayMethodAppsSettingsGetCacheNS
          CacheKeyParameters:
            - method.request.header.x-api-key
