service: apps

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, file(../api-v1/serverless.yml):custom.region.${self:provider.stage}, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  getAppSettings:
    handler: handlers/getAppSettings.default
    events:
      - http:
          path: apps/settings
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  getAppAllSettings:
    handler: handlers/getAppAllSettings.default
    events:
      - http:
          path: apps/{id}/settings
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true
  getAppInfos:
    handler: handlers/getAppInfos.default
    events:
      - http:
          path: apps/{id}/infos
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          request:
            parameters:
              paths:
                id: true
              headers:
                Authorization: true

  getAppBuilds:
    handler: handlers/getAppBuilds.default
    events:
      - http:
          path: apps/{id}/builds
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  getAppPreview:
    handler: handlers/getAppPreview.default
    events:
      - http:
          path: apps/preview/{id}
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}
          request:
            parameters:
              paths:
                id: true

  sendPreviewInfo:
    handler: handlers/sendPreviewInfo.default
    events:
      - http:
          path: apps/preview
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true

  getAppTos:
      handler: handlers/getAppTos.default
      events:
        - http:
            path: apps/{id}/tos
            method: get
            cors: true
            request:
              parameters:
                paths:
                  id: true

plugins:
  - serverless-offline
  - serverless-webpack

resources:
  Resources:
    ApiGatewayMethodAppsSettingsGet:
      Properties:
        RequestParameters:
          method.request.header.x-api-key: true
        Integration:
          RequestParameters:
            integration.request.header.x-api-key: method.request.header.x-api-key
          CacheNamespace: ApiGatewayMethodAppsSettingsGetCacheNS
          CacheKeyParameters:
            - method.request.header.x-api-key
