service: stages

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment:
    COLL_NAME: stages
    DB_NAME: crowdaaDev
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  getStages:
    handler: handlers/getStages.handleGetStages
    events:
      - http:
          path: stages
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true

  getStage:
    handler: handlers/getStage.handleGetStage
    events:
      - http:
          path: stages/{id}
          method: get
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}
          cors: true
          request:
            parameters:
              paths:
                id: true
  
  postStages:
    handler: handlers/postStage.default
    events:
      - http:
          path: stages
          method: post
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerArtistId}
          cors: true

plugins:
  - serverless-webpack

package:
  individually: true

resources:
  Outputs:
    RestApiRootResourceId:
      Description: Api Gateway stages ID
      Value:
        Ref: ApiGatewayResourceStagesIdVar
      Export:
        Name: ${self:service}:${self:provider.stage}:RestApiRootResourceId
