service: crypto

custom:
  dev:
    us-east-1:
      METAMASK_LOGIN_DOMAIN: dev-metamask.crowdaa.com
  preprod:
    eu-west-3:
      METAMASK_LOGIN_DOMAIN: preprod-metamask.crowdaa.com
  prod:
    us-east-1:
      METAMASK_LOGIN_DOMAIN: metamask.crowdaa.com
    eu-west-3:
      METAMASK_LOGIN_DOMAIN: metamask-fr.crowdaa.com

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment:
    $<<:
      ${file(../env.yml)}
    METAMASK_LOGIN_DOMAIN: '${self:custom.${self:provider.stage}.${self:provider.region}.METAMASK_LOGIN_DOMAIN}'
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  listCollections:
    handler: handlers/listCollections.default
    events:
      - http:
          path: crypto/collections
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}

  addWalletCollections:
    handler: handlers/addWalletCollections.default
    events:
      - http:
          path: crypto/collections/wallet
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}

  attachCollectionToBadge:
    handler: handlers/attachCollectionToBadge.default
    events:
      - http:
          path: nft/collections/{id}/attachBadge
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}

  checkMetamaskLoginToken:
    handler: handlers/checkMetamaskLoginToken.default
    events:
      - http:
          path: crypto/metamask/checkLoginToken
          method: put
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  prepareMetamaskLoginToken:
    handler: handlers/prepareMetamaskLoginToken.default
    events:
      - http:
          path: crypto/metamask/prepareLogin
          method: put
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}

  metamaskLoginToken:
    handler: handlers/metamaskLoginToken.default
    events:
      - http:
          path: crypto/metamask/loginToken
          method: put
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerId}

plugins:
  - serverless-offline
  - '@cruglobal/serverless-merge-config'
  - serverless-webpack

package:
  individually: true
