service: organizations

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment: ${file(../env.yml)}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
    restApiResources:
      /admin: ${cf:admin-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  createOrg:
    handler: handlers/createOrg.default
    events:
      - http:
          path: organizations
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true

  deleteOrg:
    handler: handlers/deleteOrg.default
    events:
      - http:
          path: organizations/{id}
          method: delete
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

  updateOrg:
    handler: handlers/updateOrg.default
    events:
      - http:
          path: organizations/{id}
          method: patch
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

  getUserOrgs:
    handler: handlers/getUserOrgs.default
    events:
      - http:
          path: organizations
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true

  getOrg:
    handler: handlers/getOrg.default
    events:
      - http:
          path: organizations/{id}
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

  getOrgApps:
    handler: handlers/getOrgApps.default
    events:
      - http:
          path: organizations/{id}/apps
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

  putAppInOrg:
    handler: handlers/putAppInOrg.default
    events:
      - http:
          path: organizations/{id}/apps
          method: put
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true

  getOrgWebsites:
    handler: handlers/getOrgWebsites.default
    events:
      - http:
          path: organizations/{id}/websites
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

  # Blank handlers for early testing
  inviteUserToOrg:
    handler: handlers/inviteUserToOrg.default
    events:
      - http:
          path: organizations/{id}/invite
          method: put
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

  changeUserOrgPerms:
    handler: handlers/changeUserOrgPerms.default
    events:
      - http:
          path: organizations/{id}/user/{userId}
          method: patch
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
                userId: true

  delUserOrgPerms:
    handler: handlers/delUserOrgPerms.default
    events:
      - http:
          path: organizations/{id}/user/{userId}
          method: delete
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
                userId: true

  getOrgUsers:
    handler: handlers/getOrgUsers.default
    events:
      - http:
          path: organizations/{id}/users
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

  delOrgApp:
    handler: handlers/delOrgApp.default
    events:
      - http:
          path: organizations/{id}/apps/{appId}
          method: delete
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
                userId: true

  # For debugging purposes only
  setOrgPaid:
    handler: handlers/setOrgPaid.default
    events:
      - http:
          path: organizations/{id}/debug/payment
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerAdminId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-disable-request-validators
  - serverless-prune-plugin
  - serverless-export-env

custom:
  prune:
    automatic: true
    number: 3
  serverless-disable-request-validators:
    action: delete

package:
  individually: true
