service: pressArticles

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment: ${file(../env.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
    restApiResources:
      /press: ${cf:press-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  getArticles:
    handler: handlers/getArticles.default
    events:
      - http:
          path: press/articles/
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  getAllArticles:
    handler: handlers/getAllArticles.default
    events:
      - http:
          path: press/articlesAll/
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true

  getPurchasedArticles:
    handler: handlers/getPurchasedArticles.default
    events:
      - http:
          path: press/purchasedArticles/
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true

  getArticle:
    handler: handlers/getArticle.default
    events:
      - http:
          path: press/articles/{id}
          method: get
          cors: true
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerPublicId}

  getArticleDraft:
    handler: handlers/getArticleDraft.default
    events:
      - http:
          path: press/articles/{id}/draft
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true
              paths:
                id: true

  postArticle:
    handler: handlers/postArticle.default
    events:
      - http:
          path: press/articles
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true
              querystrings:
                  autoPublish: false
                  forceCategoryId: false
                  forcePictures: false
                  xmlTagMapper: false

  putArticle:
      handler: handlers/putArticle.default
      events:
        - http:
            path: press/articles
            method: put
            cors: true
            authorizer:
              type: CUSTOM
              authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true

  publishArticle:
      handler: handlers/publishArticle.default
      events:
        - http:
            path: press/articles/{id}/publish
            method: put
            cors: true
            authorizer:
              type: CUSTOM
              authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true

  unpublishArticle:
      handler: handlers/unpublishArticle.default
      events:
        - http:
            path: press/articles/{id}/unpublish
            method: put
            cors: true
            authorizer:
              type: CUSTOM
              authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true

  purchaseArticle:
      handler: handlers/purchaseArticle.default
      events:
        - http:
            path: press/articles/{id}/purchase
            method: post
            cors: true
            authorizer:
              type: CUSTOM
              authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true

  removeArticle:
      handler: handlers/removeArticle.default
      events:
        - http:
            path: press/articles/{id}
            method: delete
            cors: true
            authorizer:
              type: CUSTOM
              authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerWithPermsId}
          request:
            parameters:
              headers:
                Authorization: true

plugins:
  - serverless-webpack
  - serverless-export-env

package:
  individually: true

resources:
  Outputs:
    RestApiRootResourcePressId:
      Description: Api Gateway pressArticles ID
      Value:
        Ref: ApiGatewayResourcePressArticles
      Export:
        Name: ${self:service}:${self:provider.stage}:RestApiRootResourcePressId
    RestApiRootResourcePressArticlesId:
      Description: Api Gateway pressArticlesIdVar ID
      Value:
        Ref: ApiGatewayResourcePressArticlesIdVar
      Export:
        Name: ${self:service}:${self:provider.stage}:RestApiRootResourcePressArticlesId
