service: pressArticles

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, "dev"}
  memorySize: 128
  timeout: 30
  environment:
    COLL_NAME: pressArticles
    DB_NAME: crowdaaDev
    MONGO_URL: ${cf:api-v1-${self:provider.stage}.MongoURL}
    STAGE: ${self:provider.stage}
  apiGateway:
    restApiId: ${cf:api-v1-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:api-v1-${self:provider.stage}.RestApiRootResourceId}
    restApiResources:
      /press: ${cf:press-${self:provider.stage}.RestApiRootResourceId}
  region: ${opt:region, "us-east-1"}
  deploymentBucket: ms-deployment-${self:provider.region}

functions:
  getArticles:
    handler: handlers/getArticles.default
    events:
      - http:
          path: press/articles/
          method: get
          cors: true

  getAllArticles:
    handler: handlers/getAllArticles.default
    events:
      - http:
          path: press/articlesAll/
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerRoleId}

  getArticle:
    handler: handlers/getArticle.default
    events:
      - http:
          path: press/articles/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

  getArticleDraft:
    handler: handlers/getArticleDraft.default
    events:
      - http:
          path: press/articles/{id}/draft
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerRoleId}
          request:
            parameters:
              paths:
                id: true

  postArticle:
    handler: handlers/postArticle.default
    events:
      - http:
          path: press/articles
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerRoleId}
          request:
            parameters:
              querystrings:
                  autoPublish: false
                  forceCategoryId: false
                  forcePictures: false
                  xmlTagMapper: false

  putArticle:
      handler: handlers/putArticle.default
      events:
        - http:
            path: press/articles
            method: put
            cors: true
            authorizer:
              type: CUSTOM
              authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerRoleId}

  publishArticle:
      handler: handlers/publishArticle.default
      events:
        - http:
            path: press/articles/{id}/publish
            method: put
            cors: true
            authorizer:
              type: CUSTOM
              authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerRoleId}

  unpublishArticle:
      handler: handlers/unpublishArticle.default
      events:
        - http:
            path: press/articles/{id}/unpublish
            method: put
            cors: true
            authorizer:
              type: CUSTOM
              authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerRoleId}

  removeArticle:
      handler: handlers/removeArticle.default
      events:
        - http:
            path: press/articles/{id}
            method: delete
            cors: true
            authorizer:
              type: CUSTOM
              authorizerId: ${cf:account-${self:provider.stage}.ApiGatewayAuthorizerRoleId}
plugins:
  - serverless-webpack

package:
  individually: true
