openapi: "3.0.3"
info:
  version: "2020-11-04T10:36:57Z"
  title: "dev-api-v1"
host: "dev-api.aws.crowdaa.com"
basePath: "/v1"
schemes:
- "https"
components:
  schemas: {}
  responses: {}
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-Api-Key
      in: header
      description: The API key, linked to a single application ID, and required in most requests
security:
  - apiKey: []
paths: {}
