openapi: "3.0.3"
info:
  version: "2020-11-04T10:36:57Z"
  title: "dev-api-v1"
servers:
- url: https://dev-api.aws.crowdaa.com/{basePath}
  description: Development endpoint
  variables:
    basePath:
      default: v1
- url: https://preprod-api.aws.crowdaa.com/{basePath}
  description: Pre-production endpoint
  variables:
    basePath:
      default: v1
- url: https://api.aws.crowdaa.com/{basePath}
  description: Production endpoint
  variables:
    basePath:
      default: v1
basePath: "/v1"
schemes:
- "https"
components:
  schemas: {}
  responses: {}
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-Api-Key
      in: header
      description: The API key, linked to a single application ID, and required in most requests
security:
  - apiKey: []
paths: {}
